// frontend/src/components/Layout.tsx
import { createSignal, Show, For } from 'solid-js';
import { useNavigate, useLocation } from '@solidjs/router';
import { getCurrentUser, setCurrentUser, ROLE_LABELS, api } from '../lib/api';

export default function Layout(props: { children: any }) {
  const navigate = useNavigate();
  const location = useLocation();
  const [user, setUser] = createSignal(getCurrentUser());

  const logout = () => {
    setCurrentUser(null);
    setUser(null);
    navigate('/login');
  };

  const navItems = () => {
    const role = user()?.role;
    const items = [
      { path: '/', label: '种植任务', icon: '📋' },
      { path: '/overdue', label: '到期预警', icon: '⏰' },
    ];
    if (role === 'cooperative_director' || role === 'agricultural_technician') {
      items.push({ path: '/audit', label: '审计轨迹', icon: '📝' });
    }
    return items;
  };

  const isActive = (path: string) => {
    if (path === '/') return location.pathname === '/';
    return location.pathname.startsWith(path);
  };

  return (
    <div class="min-h-screen flex">
      <aside class="w-64 bg-primary-800 text-white flex flex-col shrink-0">
        <div class="p-4 border-b border-primary-700">
          <h1 class="text-lg font-bold">🌾 农业合作社</h1>
          <p class="text-primary-200 text-xs mt-1">月底集中处理种植任务</p>
        </div>

        <nav class="flex-1 py-4">
          <For each={navItems()}>
            {(item) => (
              <a
                href={item.path}
                class={`flex items-center px-4 py-3 text-sm transition-colors ${
                  isActive(item.path)
                    ? 'bg-primary-700 text-white font-medium'
                    : 'text-primary-100 hover:bg-primary-700/50'
                }`}
                onClick={(e) => {
                  e.preventDefault();
                  navigate(item.path);
                }}
              >
                <span class="mr-3">{item.icon}</span>
                {item.label}
              </a>
            )}
          </For>
        </nav>

        <Show when={user()}>
          <div class="p-4 border-t border-primary-700">
            <div class="flex items-center gap-3">
              <div class="w-8 h-8 rounded-full bg-primary-600 flex items-center justify-center text-sm font-medium">
                {user()!.displayName[0]}
              </div>
              <div class="flex-1 min-w-0">
                <p class="text-sm font-medium truncate">{user()!.displayName}</p>
                <p class="text-xs text-primary-200">{ROLE_LABELS[user()!.role]}</p>
              </div>
              <button
                onClick={logout}
                class="text-primary-200 hover:text-white text-xs"
                title="退出登录"
              >
                退出
              </button>
            </div>
          </div>
        </Show>
      </aside>

      <main class="flex-1 overflow-auto">
        {props.children}
      </main>
    </div>
  );
}

// frontend/src/routes/layout.tsx
import { component$, useSignal, $, useVisibleTask$, Slot } from "@builder.io/qwik";
import { Link, useLocation } from "@builder.io/qwik-city";
import { loadAuthFromStorage, getAuth, clearAuth, ROLE_LABELS, type UserRole } from "../stores/auth";

export default component$(() => {
  const collapsed = useSignal(false);
  const authData = useSignal(getAuth());

  const loc = useLocation();

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(() => {
    loadAuthFromStorage();
    authData.value = getAuth();
  });

  const navItems = [
    { href: "/", label: "审核单列表", icon: "📋" },
    { href: "/batch", label: "批量处理", icon: "⚡" },
    { href: "/expiry", label: "到期预警", icon: "⏰" },
  ];

  const isActive = (href: string) => {
    if (href === "/") return loc.url.pathname === "/";
    return loc.url.pathname.startsWith(href);
  };

  const handleLogout = $(() => {
    clearAuth();
    window.location.href = "/login";
  });

  if (loc.url.pathname === "/login") {
    return <Slot />;
  }

  if (!authData.value) {
    if (typeof window !== "undefined") {
      window.location.href = "/login";
    }
    return <div class="flex items-center justify-center h-screen">跳转登录中...</div>;
  }

  const role = authData.value.role as UserRole;

  return (
    <div class="flex h-screen overflow-hidden">
      <aside
        class={`bg-white border-r border-stone-200 flex flex-col transition-all duration-200 ${
          collapsed.value ? "w-16" : "w-56"
        }`}
      >
        <div class="h-14 flex items-center justify-between px-4 border-b border-stone-200">
          {!collapsed.value && (
            <span class="text-primary font-bold text-sm truncate">审核单系统</span>
          )}
          <button
            onClick$={() => (collapsed.value = !collapsed.value)}
            class="text-stone-400 hover:text-primary p-1 rounded"
          >
            {collapsed.value ? "▶" : "◀"}
          </button>
        </div>
        <nav class="flex-1 p-2 space-y-1">
          {navItems.map((item) => (
            <Link
              key={item.href}
              href={item.href}
              class={`flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm transition-all no-underline ${
                isActive(item.href)
                  ? "bg-primary text-white"
                  : "text-stone-600 hover:bg-stone-100 hover:text-primary"
              }`}
            >
              <span class="text-base">{item.icon}</span>
              {!collapsed.value && <span>{item.label}</span>}
            </Link>
          ))}
        </nav>
        <div class="border-t border-stone-200 p-3">
          {!collapsed.value && (
            <div class="text-xs text-stone-500 mb-2">
              <div class="font-medium text-stone-700">{authData.value.username}</div>
              <div>{ROLE_LABELS[role]}</div>
            </div>
          )}
          <button
            onClick$={handleLogout}
            class="w-full text-xs text-stone-400 hover:text-status-red transition-colors py-1"
          >
            {collapsed.value ? "🚪" : "退出登录"}
          </button>
        </div>
      </aside>
      <main class="flex-1 overflow-auto">
        <Slot />
      </main>
    </div>
  );
});
