// frontend/src/app/pages/login/login.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="login-container">
      <div class="login-card">
        <h1 class="login-title">货运物流公司</h1>
        <h2 class="login-subtitle">月底集中处理运输订单系统</h2>
        <form class="login-form" (ngSubmit)="onSubmit()">
          <div class="form-group">
            <label>用户名</label>
            <input type="text" [(ngModel)]="username" name="username" required placeholder="请输入用户名" />
          </div>
          <div class="form-group">
            <label>密码</label>
            <input type="password" [(ngModel)]="password" name="password" required placeholder="请输入密码" />
          </div>
          <div class="error-message" *ngIf="error()">{{ error() }}</div>
          <button type="submit" class="btn btn-primary btn-block" [disabled]="loading()">
            {{ loading() ? '登录中...' : '登录' }}
          </button>
        </form>
        <div class="demo-accounts">
          <h3>演示账号</h3>
          <ul>
            <li (click)="quickLogin('kefu', '123456')">
              <span class="role">客服专员</span>
              <span class="account">kefu / 123456</span>
            </li>
            <li (click)="quickLogin('diaodu', '123456')">
              <span class="role">调度主管</span>
              <span class="account">diaodu / 123456</span>
            </li>
            <li (click)="quickLogin('yunying', '123456')">
              <span class="role">运营经理</span>
              <span class="account">yunying / 123456</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .login-container {
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      padding: 20px;
    }
    .login-card {
      background: #fff;
      border-radius: 8px;
      padding: 40px;
      width: 100%;
      max-width: 440px;
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
    }
    .login-title {
      font-size: 24px;
      font-weight: 600;
      text-align: center;
      color: #1f1f1f;
      margin-bottom: 4px;
    }
    .login-subtitle {
      font-size: 16px;
      font-weight: 400;
      text-align: center;
      color: #666;
      margin-bottom: 32px;
    }
    .form-group { margin-bottom: 20px; }
    .form-group label { display: block; margin-bottom: 8px; font-size: 14px; color: #333; }
    .form-group input {
      width: 100%; padding: 10px 12px; border: 1px solid #d9d9d9;
      border-radius: 4px; font-size: 14px; outline: none; transition: border-color 0.2s;
    }
    .form-group input:focus { border-color: #1677ff; }
    .btn-primary {
      background: #1677ff; color: #fff; border: none; padding: 10px 24px;
      border-radius: 4px; font-size: 14px; transition: background 0.2s;
    }
    .btn-primary:hover { background: #4096ff; }
    .btn-primary:disabled { background: #91caff; cursor: not-allowed; }
    .btn-block { width: 100%; }
    .error-message { color: #ff4d4f; margin-bottom: 12px; font-size: 13px; }
    .demo-accounts { margin-top: 24px; padding-top: 24px; border-top: 1px solid #f0f0f0; }
    .demo-accounts h3 { font-size: 14px; font-weight: 600; margin-bottom: 12px; color: #333; }
    .demo-accounts ul { list-style: none; }
    .demo-accounts li {
      display: flex; justify-content: space-between; align-items: center;
      padding: 10px 12px; background: #fafafa; border-radius: 4px;
      margin-bottom: 8px; cursor: pointer; transition: background 0.2s;
    }
    .demo-accounts li:hover { background: #e6f4ff; }
    .demo-accounts .role { font-weight: 500; color: #1677ff; font-size: 14px; }
    .demo-accounts .account { color: #666; font-size: 13px; font-family: monospace; }
  `]
})
export class LoginComponent {
  username = '';
  password = '';
  loading = signal(false);
  error = signal('');

  constructor(private authService: AuthService, private router: Router) {}

  onSubmit() {
    if (!this.username || !this.password) {
      this.error.set('请输入用户名和密码');
      return;
    }
    this.doLogin(this.username, this.password);
  }

  quickLogin(username: string, password: string) {
    this.username = username;
    this.password = password;
    this.doLogin(username, password);
  }

  private doLogin(username: string, password: string) {
    this.loading.set(true);
    this.error.set('');
    this.authService.login(username, password).subscribe({
      next: () => {
        this.loading.set(false);
        this.router.navigate(['/orders']);
      },
      error: (err) => {
        this.loading.set(false);
        this.error.set(err?.error?.detail || err?.error?.message || '登录失败，请检查用户名和密码');
      }
    });
  }
}

// frontend/src/routes/login/+page.svelte
<script>
	import { goto } from '$app/navigation';
	import { userStore } from '$lib/store.js';
	import { onMount } from 'svelte';

	let username = '';
	let password = '';
	let loading = false;
	let error = '';

	const demoUsers = [
		{ username: 'register01', name: '张登记（融资申请登记员）' },
		{ username: 'auditor01', name: '李审核（融资申请审核主管）' },
		{ username: 'reviewer01', name: '王复核（供应链金融平台复核负责人）' },
		{ username: 'admin', name: '系统管理员（全角色）' }
	];

	onMount(() => {
		const token = localStorage.getItem('token');
		if (token) {
			goto('/');
		}
	});

	async function handleLogin() {
		if (!username || !password) {
			error = '请输入用户名和密码';
			return;
		}

		loading = true;
		error = '';

		try {
			await userStore.login(username, password);
			goto('/');
		} catch (e) {
			error = e.message || '登录失败';
		} finally {
			loading = false;
		}
	}

	function quickLogin(u) {
		username = u.username;
		password = '123456';
	}

	function handleKeydown(e) {
		if (e.key === 'Enter') {
			handleLogin();
		}
	}
</script>

<div class="login-page">
	<div class="login-container">
		<div class="login-left">
			<div class="login-brand">
				<div class="brand-icon">💳</div>
				<h1>供应链金融平台</h1>
				<p>月底集中处理融资申请单系统</p>
			</div>
			<div class="login-features">
				<div class="feature-item">
					<span class="feature-icon">🔒</span>
					<span>严格的角色权限控制</span>
				</div>
				<div class="feature-item">
					<span class="feature-icon">📋</span>
					<span>完整的处理流程跟踪</span>
				</div>
				<div class="feature-item">
					<span class="feature-icon">⚠️</span>
					<span>智能异常拦截预警</span>
				</div>
				<div class="feature-item">
					<span class="feature-icon">⏱️</span>
					<span>到期预警与逾期管理</span>
				</div>
			</div>
		</div>
		<div class="login-right">
			<div class="login-form-container">
				<h2>系统登录</h2>
				<p class="form-subtitle">请输入您的账号信息</p>
				
				{#if error}
					<div class="error-box">{error}</div>
				{/if}

				<div class="form-group">
					<label>用户名</label>
					<input 
						type="text" 
						bind:value={username} 
						placeholder="请输入用户名"
						on:keydown={handleKeydown}
					/>
				</div>

				<div class="form-group">
					<label>密码</label>
					<input 
						type="password" 
						bind:value={password} 
						placeholder="请输入密码"
						on:keydown={handleKeydown}
					/>
				</div>

				<button 
					class="login-btn" 
					on:click={handleLogin}
					disabled={loading}
				>
					{loading ? '登录中...' : '登 录'}
				</button>

				<div class="demo-users">
					<p class="demo-title">演示账号（点击快速填入）：</p>
					<div class="demo-list">
						{#each demoUsers as u}
							<button class="demo-btn" on:click={() => quickLogin(u)}>
								{u.name}
							</button>
						{/each}
					</div>
					<p class="demo-hint">默认密码：123456</p>
				</div>
			</div>
		</div>
	</div>
</div>

<style>
	.login-page {
		min-height: 100vh;
		display: flex;
		align-items: center;
		justify-content: center;
		background: linear-gradient(135deg, #1890ff 0%, #096dd9 50%, #0050b3 100%);
		padding: 20px;
	}

	.login-container {
		width: 100%;
		max-width: 960px;
		display: flex;
		background: white;
		border-radius: 12px;
		overflow: hidden;
		box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
	}

	.login-left {
		flex: 1;
		background: linear-gradient(135deg, #1890ff 0%, #096dd9 100%);
		color: white;
		padding: 48px 40px;
		display: flex;
		flex-direction: column;
		justify-content: space-between;
	}

	.login-brand {
		text-align: center;
	}

	.brand-icon {
		font-size: 64px;
		margin-bottom: 16px;
	}

	.login-brand h1 {
		font-size: 28px;
		margin: 0 0 8px 0;
	}

	.login-brand p {
		font-size: 14px;
		opacity: 0.85;
		margin: 0;
	}

	.login-features {
		display: flex;
		flex-direction: column;
		gap: 16px;
	}

	.feature-item {
		display: flex;
		align-items: center;
		gap: 12px;
		font-size: 14px;
	}

	.feature-icon {
		font-size: 20px;
	}

	.login-right {
		flex: 1;
		padding: 48px 40px;
		display: flex;
		align-items: center;
	}

	.login-form-container {
		width: 100%;
	}

	.login-form-container h2 {
		font-size: 24px;
		margin: 0 0 8px 0;
		color: #333;
	}

	.form-subtitle {
		color: #999;
		font-size: 14px;
		margin: 0 0 24px 0;
	}

	.error-box {
		background: #fff2f0;
		border: 1px solid #ffccc7;
		color: #ff4d4f;
		padding: 10px 12px;
		border-radius: 4px;
		margin-bottom: 16px;
		font-size: 13px;
	}

	.form-group {
		margin-bottom: 20px;
	}

	.form-group label {
		display: block;
		margin-bottom: 8px;
		font-size: 14px;
		color: #333;
		font-weight: 500;
	}

	.form-group input {
		width: 100%;
		padding: 12px 16px;
		border: 1px solid #d9d9d9;
		border-radius: 6px;
		font-size: 14px;
		transition: all 0.2s;
		box-sizing: border-box;
	}

	.form-group input:focus {
		outline: none;
		border-color: #1890ff;
		box-shadow: 0 0 0 2px rgba(24, 144, 255, 0.2);
	}

	.login-btn {
		width: 100%;
		padding: 12px;
		background: linear-gradient(90deg, #1890ff 0%, #096dd9 100%);
		color: white;
		border: none;
		border-radius: 6px;
		font-size: 16px;
		font-weight: 500;
		cursor: pointer;
		transition: all 0.2s;
	}

	.login-btn:hover:not(:disabled) {
		opacity: 0.9;
		transform: translateY(-1px);
	}

	.login-btn:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.demo-users {
		margin-top: 24px;
		padding-top: 20px;
		border-top: 1px solid #f0f0f0;
	}

	.demo-title {
		font-size: 13px;
		color: #666;
		margin: 0 0 12px 0;
	}

	.demo-list {
		display: flex;
		flex-wrap: wrap;
		gap: 8px;
	}

	.demo-btn {
		padding: 6px 12px;
		font-size: 12px;
		background: #f5f5f5;
		border: 1px solid #d9d9d9;
		border-radius: 4px;
		cursor: pointer;
		transition: all 0.2s;
		color: #333;
	}

	.demo-btn:hover {
		background: #e6f7ff;
		border-color: #91d5ff;
		color: #1890ff;
	}

	.demo-hint {
		font-size: 12px;
		color: #999;
		margin: 12px 0 0 0;
	}
</style>
