// frontend/app.vue
<template>
  <div class="app-layout">
    <header class="app-header">
      <div class="header-left">
        <h1 class="app-title">社区健身房 - 月底集中处理会员入会单系统</h1>
      </div>
      <div class="header-right">
        <div v-if="auth.isLoggedIn.value" class="user-info">
          <span class="user-name">{{ auth.currentUser.value?.full_name }}</span>
          <span class="user-role tag tag-pending">{{ ROLE_LABELS[auth.currentUser.value?.role || 'registration_clerk'] }}</span>
          <button class="btn btn-sm" @click="showRoleSwitcher = true">切换角色</button>
          <button class="btn btn-sm" @click="handleLogout">退出</button>
        </div>
      </div>
    </header>
    <main class="app-main">
      <NuxtPage />
    </main>

    <div v-if="showRoleSwitcher" class="modal-mask" @click.self="showRoleSwitcher = false">
      <div class="modal">
        <div class="modal-header">
          <span>切换角色（演示用）</span>
          <button class="close-btn" @click="showRoleSwitcher = false">×</button>
        </div>
        <div class="modal-body">
          <p class="text-secondary mb-4">选择不同角色登录，体验不同岗位的操作权限：</p>
          <div class="role-list">
            <div
              v-for="account in demoAccounts"
              :key="account.username"
              class="role-item"
              @click="switchRole(account.username)"
            >
              <div class="role-name">{{ account.full_name }}</div>
              <div class="role-tag tag" :class="getRoleTagClass(account.role)">
                {{ ROLE_LABELS[account.role] }}
              </div>
              <div class="role-username text-sm text-tertiary">{{ account.username }} / 123456</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useAuth } from '~/composables/useAuth'
import { ROLE_LABELS, type RoleEnum } from '~/types'

const auth = useAuth()
const showRoleSwitcher = ref(false)

const demoAccounts = [
  { username: 'clerk1', full_name: '张登记', role: 'registration_clerk' as RoleEnum },
  { username: 'clerk2', full_name: '李文员', role: 'registration_clerk' as RoleEnum },
  { username: 'supervisor1', full_name: '王审核', role: 'audit_supervisor' as RoleEnum },
  { username: 'lead1', full_name: '赵复核', role: 'review_lead' as RoleEnum },
]

onMounted(() => {
  auth.initAuth()
  if (!auth.isLoggedIn.value) {
    auth.login('clerk1', '123456').catch(() => {})
  }
})

const getRoleTagClass = (role: RoleEnum) => {
  switch (role) {
    case 'registration_clerk':
      return 'tag-pending'
    case 'audit_supervisor':
      return 'tag-normal'
    case 'review_lead':
      return 'tag-approaching'
    default:
      return ''
  }
}

const switchRole = async (username: string) => {
  try {
    await auth.login(username, '123456')
    showRoleSwitcher.value = false
    navigateTo('/')
  } catch (e) {
    console.error('切换角色失败', e)
  }
}

const handleLogout = () => {
  auth.logout()
  navigateTo('/')
}
</script>

<style scoped>
.app-layout {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.app-header {
  background-color: white;
  border-bottom: 1px solid #f0f0f0;
  padding: 0 24px;
  height: 60px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  position: sticky;
  top: 0;
  z-index: 100;
}

.app-title {
  font-size: 18px;
  font-weight: 600;
  color: var(--text-primary);
}

.header-right {
  display: flex;
  align-items: center;
  gap: 12px;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 8px;
}

.user-name {
  font-weight: 500;
}

.app-main {
  flex: 1;
  padding: 20px 24px;
}

.role-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.role-item {
  padding: 12px 16px;
  border: 1px solid #f0f0f0;
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.2s;
  display: flex;
  align-items: center;
  gap: 12px;
}

.role-item:hover {
  border-color: var(--primary-color);
  background-color: #e6f7ff;
}

.role-name {
  font-weight: 500;
  min-width: 80px;
}
</style>

// frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet, RouterLink, Router } from '@angular/router';
import { AuthService } from './services/auth.service';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, RouterLink],
  template: `
    <div class="app-layout">
      <header class="app-header" *ngIf="authService.isLoggedIn()">
        <div class="header-left">
          <h1 class="app-title">货运物流公司-月底集中处理运输订单系统</h1>
        </div>
        <div class="header-right">
          <span class="user-info" *ngIf="authService.currentUser()">
            {{ authService.currentUser()?.full_name }}
            <span class="role-tag">{{ authService.currentUser()?.role }}</span>
          </span>
          <button class="btn btn-link" (click)="switchRole()">切换角色</button>
          <button class="btn btn-link" (click)="logout()">退出</button>
        </div>
      </header>
      <nav class="app-nav" *ngIf="authService.isLoggedIn()">
        <a routerLink="/orders" routerLinkActive="active" class="nav-item">运输订单登记</a>
        <a routerLink="/orders?tab=review" routerLinkActive="active" class="nav-item">过程核验</a>
        <a routerLink="/orders?tab=archive" routerLinkActive="active" class="nav-item">复核归档</a>
        <a routerLink="/warnings" routerLinkActive="active" class="nav-item">到期预警</a>
      </nav>
      <main class="app-main">
        <router-outlet></router-outlet>
      </main>
    </div>
  `,
  styles: [`
    .app-layout { min-height: 100vh; display: flex; flex-direction: column; }
    .app-header {
      background: #001529; color: #fff; padding: 0 24px; height: 64px;
      display: flex; justify-content: space-between; align-items: center;
    }
    .app-title { font-size: 18px; font-weight: 600; color: #fff; }
    .header-right { display: flex; align-items: center; gap: 16px; }
    .user-info { font-size: 14px; }
    .role-tag {
      display: inline-block; margin-left: 8px; padding: 2px 8px;
      background: #1677ff; color: #fff; border-radius: 4px; font-size: 12px;
    }
    .app-nav {
      background: #fff; border-bottom: 1px solid #f0f0f0;
      padding: 0 24px; display: flex; gap: 4px;
    }
    .nav-item {
      padding: 14px 20px; color: #000000d9; font-size: 14px;
      border-bottom: 2px solid transparent; transition: all 0.2s;
    }
    .nav-item:hover { color: #1677ff; }
    .nav-item.active { color: #1677ff; border-bottom-color: #1677ff; font-weight: 500; }
    .app-main { flex: 1; padding: 24px; }
    .btn { padding: 6px 16px; border-radius: 4px; border: 1px solid #d9d9d9; background: #fff; font-size: 14px; }
    .btn:hover { border-color: #1677ff; color: #1677ff; }
    .btn-link { border: none; background: transparent; color: #1677ff; padding: 4px 8px; }
    .btn-link:hover { color: #4096ff; }
  `]
})
export class AppComponent {
  constructor(public authService: AuthService, private router: Router) {}

  logout() {
    this.authService.logout();
    this.router.navigate(['/login']);
  }

  switchRole() {
    this.authService.logout();
    this.router.navigate(['/login']);
  }
}
