// frontend/src/app/components/batch-result-modal/batch-result-modal.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { BatchResult } from '../../models/launch-plan';

@Component({
  selector: 'app-batch-result-modal',
  template: `
    <div class="modal-overlay" (click.self)="close.emit()">
      <div class="modal" style="width:720px;max-width:92vw">
        <div class="modal-header">
          <span>📊 批量处理结果</span>
          <button class="modal-close" (click)="close.emit()">×</button>
        </div>
        <div class="modal-body">
          <div class="summary flex gap-md wrap mb-md">
            <div class="stat-card" style="flex:1;background:#f0f9ff">
              <div class="label">处理总数</div>
              <div class="value" style="color:#0369a1;font-size:24px">{{result.total}}</div>
            </div>
            <div class="stat-card" style="flex:1;background:#f0f9eb">
              <div class="label">成功</div>
              <div class="value" style="color:#15803d;font-size:24px">{{result.success}}</div>
            </div>
            <div class="stat-card" style="flex:1;background:#fef2f2">
              <div class="label">失败 / 拦截</div>
              <div class="value" style="color:#b91c1c;font-size:24px">{{result.failed}}</div>
            </div>
          </div>

          <div class="section-title">逐条明细</div>
          <table class="data-table">
            <thead>
              <tr>
                <th>计划单号</th>
                <th>客户名称</th>
                <th>结果</th>
                <th>成功/失败原因</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let item of result.items">
                <td style="font-weight:600">{{item.plan_no || item.id}}</td>
                <td>{{item.customer_name || '-'}}</td>
                <td>
                  <span *ngIf="item.success" class="tag tag-success">✅ 成功</span>
                  <span *ngIf="!item.success" class="tag tag-danger">❌ 失败</span>
                </td>
                <td style="max-width:380px">{{item.reason}}</td>
              </tr>
            </tbody>
          </table>

          <div *ngIf="result.failed > 0" class="alert alert-warning mt-md">
            💡 提示：失败 / 被拦截的单据请在详情页逐项处理补正，系统已在处理记录中留下补正动作和异常原因。
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" (click)="close.emit()">确定</button>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .data-table th, .data-table td {
      padding: 10px 8px;
      text-align: left;
      border-bottom: 1px solid var(--border);
      font-size: 13px;
    }
    .data-table th { background: var(--bg-light); }
  `],
})
export class BatchResultModalComponent {
  @Input() result!: BatchResult;
  @Output() close = new EventEmitter();
}

// frontend/src/components/BatchResultModal.jsx
import React from 'react'
import { STATUS_COLOR } from '../api.js'

export default function BatchResultModal({ data, onClose }) {
  const successRate = data.total > 0 ? Math.round(data.success_count / data.total * 100) : 0
  return (
    <div className="modal-mask" onClick={onClose}>
      <div className="modal large" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="modal-title">📊 批量处理结果 - 共 {data.total} 条</div>
          <button className="modal-close" onClick={onClose}>×</button>
        </div>
        <div className="modal-body">
          <div className="stats-grid" style={{ marginBottom: 20 }}>
            <div className="stat-card success">
              <div className="stat-label">✅ 成功</div>
              <div className="stat-value">{data.success_count}</div>
            </div>
            <div className="stat-card danger">
              <div className="stat-label">❌ 失败</div>
              <div className="stat-value">{data.fail_count}</div>
            </div>
            <div className="stat-card info">
              <div className="stat-label">📈 成功率</div>
              <div className="stat-value">{successRate}%</div>
            </div>
          </div>
          <div className="progress-bar" style={{ marginBottom: 20 }}>
            <div className="progress-fill" style={{ width: successRate + '%' }}></div>
          </div>
          <div className="batch-result-list">
            {data.results.map(r => (
              <div key={r.id} className={'batch-result-item ' + (r.success ? 'success' : 'fail')}>
                <span className="batch-id">单号 #{r.id}</span>
                <span>{r.success ? '✅' : '❌'}</span>
                <span style={{ flex: 1 }}>{r.message}</span>
                {r.status && (
                  <span className="tag" style={{
                    background: STATUS_COLOR[r.status] + '22',
                    color: STATUS_COLOR[r.status],
                    border: `1px solid ${STATUS_COLOR[r.status]}55`
                  }}>{r.status}</span>
                )}
              </div>
            ))}
          </div>
        </div>
        <div className="modal-footer">
          <button className="btn btn-primary" onClick={onClose}>知道了</button>
        </div>
      </div>
    </div>
  )
}
