// frontend/src/routes/login/index.tsx
import { component$, useStore, $ } from "@builder.io/qwik";
import { type DocumentHead, useNavigate } from "@builder.io/qwik-city";
import { api } from "~/services/api";
import { config } from "~/config";

export default component$(() => {
  const nav = useNavigate();
  const state = useStore({
    username: "",
    password: "",
    loading: false,
    error: "",
  });

  const handleLogin = $(async () => {
    if (!state.username || !state.password) {
      state.error = "请输入用户名和密码";
      return;
    }

    state.loading = true;
    state.error = "";

    try {
      await api.auth.login({
        username: state.username,
        password: state.password,
      });
      await nav("/");
    } catch (e: any) {
      state.error = e.message || "登录失败";
    } finally {
      state.loading = false;
    }
  });

  return (
    <div
      style={{
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        padding: "20px",
      }}
    >
      <div
        style={{
          background: "white",
          borderRadius: "16px",
          padding: "40px",
          width: "100%",
          maxWidth: "420px",
          boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
        }}
      >
        <div style={{ textAlign: "center", marginBottom: "32px" }}>
          <div
            style={{
              fontSize: "28px",
              fontWeight: "700",
              color: "#1f2937",
              marginBottom: "8px",
            }}
          >
            展会展商申请系统
          </div>
          <div style={{ fontSize: "14px", color: "#6b7280" }}>
            展会主办方-月底集中处理展商申请系统
          </div>
        </div>

        {state.error && (
          <div class="alert alert-error">{state.error}</div>
        )}

        <div class="form-group">
          <label class="form-label">用户名</label>
          <input
            class="form-input"
            type="text"
            value={state.username}
            onInput$={(e) => {
              state.username = (e.target as HTMLInputElement).value;
            }}
            placeholder="请输入用户名"
            disabled={state.loading}
          />
        </div>

        <div class="form-group">
          <label class="form-label">密码</label>
          <input
            class="form-input"
            type="password"
            value={state.password}
            onInput$={(e) => {
              state.password = (e.target as HTMLInputElement).value;
            }}
            placeholder="请输入密码"
            disabled={state.loading}
            onKeyDown$={(e) => {
              if (e.key === "Enter") {
                handleLogin();
              }
            }}
          />
        </div>

        <button
          class="btn btn-primary"
          style={{ width: "100%", height: "44px", fontSize: "15px" }}
          onClick$={handleLogin}
          disabled={state.loading}
        >
          {state.loading ? "登录中..." : "登 录"}
        </button>

        <div style={{ marginTop: "24px", paddingTop: "20px", borderTop: "1px solid #e5e7eb" }}>
          <div style={{ fontSize: "13px", color: "#6b7280", marginBottom: "12px" }}>
            演示账号：
          </div>
          <div style={{ fontSize: "12px", color: "#4b5563", lineHeight: "1.8" }}>
            <div>展商登记员：registrar1 / 123456</div>
            <div>展商审核主管：supervisor1 / 123456</div>
            <div>主办方复核负责人：leader1 / 123456</div>
          </div>
        </div>
      </div>
    </div>
  );
});

export const head: DocumentHead = {
  title: "登录 - 展会主办方-月底集中处理展商申请系统",
};

// frontend/src/components/Login.tsx
import { useState, useEffect } from 'react';
import { api, type User } from '../lib/api';

const demoAccounts: { username: string; password: string; name: string; role: string }[] = [
  { username: 'registrar', password: '123456', name: '李登记员', role: '学员报名登记员' },
  { username: 'auditor', password: '123456', name: '王审核主管', role: '学员报名审核主管' },
  { username: 'reviewer', password: '123456', name: '张复核校长', role: '职业技能学校复核负责人' },
];

export default function Login({ onLogin }: { onLogin: (user: User) => void }) {
  const [username, setUsername] = useState('registrar');
  const [password, setPassword] = useState('123456');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleLogin = async (u?: string, p?: string) => {
    setLoading(true);
    setError('');
    try {
      const res = await api.login(u || username, p || password);
      onLogin(res.user);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    }}>
      <div className="card" style={{ width: '420px', padding: '32px' }}>
        <h1 style={{ textAlign: 'center', marginBottom: '8px', color: '#1e3a8a' }}>
          职业技能学校
        </h1>
        <p style={{ textAlign: 'center', color: '#6b7280', marginBottom: '24px' }}>
          月底集中处理学员报名单系统
        </p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '4px', fontSize: '14px', fontWeight: 500 }}>
              用户名
            </label>
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              style={{ width: '100%' }}
              placeholder="请输入用户名"
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '4px', fontSize: '14px', fontWeight: 500 }}>
              密码
            </label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              style={{ width: '100%' }}
              placeholder="请输入密码"
              onKeyDown={(e) => e.key === 'Enter' && handleLogin()}
            />
          </div>

          {error && (
            <div style={{ padding: '10px', background: '#fee2e2', color: '#991b1b', borderRadius: '6px', fontSize: '14px' }}>
              {error}
            </div>
          )}

          <button
            className="btn btn-primary"
            onClick={() => handleLogin()}
            disabled={loading}
            style={{ width: '100%', padding: '12px', fontSize: '16px' }}
          >
            {loading ? '登录中...' : '登 录'}
          </button>
        </div>

        <div style={{ marginTop: '24px', paddingTop: '20px', borderTop: '1px solid #e5e7eb' }}>
          <p style={{ fontSize: '13px', color: '#6b7280', marginBottom: '12px' }}>快速登录演示账号：</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {demoAccounts.map((acc) => (
              <button
                key={acc.username}
                onClick={() => handleLogin(acc.username, acc.password)}
                style={{
                  padding: '10px',
                  border: '1px solid #d1d5db',
                  borderRadius: '6px',
                  background: 'white',
                  cursor: 'pointer',
                  textAlign: 'left',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                }}
              >
                <span style={{ fontWeight: 500 }}>{acc.name}</span>
                <span style={{ fontSize: '12px', color: '#6b7280' }}>{acc.role}</span>
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
