// frontend/src/components/BatchProcessModal.jsx
import { createSignal, For } from 'solid-js';
import { api } from '../api';

const actionLabels = {
  accept: '接单',
  process: '处理流转',
  verify: '核实流转',
  return: '退回补正',
  approve: '审批通过',
  reject: '不予通过',
};

export default function BatchProcessModal({ applications, action, onClose, onSuccess }) {
  const [comment, setComment] = createSignal('');
  const [processing, setProcessing] = createSignal(false);
  const [results, setResults] = createSignal(null);
  const [error, setError] = createSignal('');

  const handleSubmit = async () => {
    setProcessing(true);
    setError('');
    setResults(null);

    try {
      const items = applications.map((app) => ({
        application_id: app.id,
        version: app.version,
        action: action,
        comment: comment(),
      }));

      const data = await api.batchProcess(items);
      setResults(data);
      onSuccess && onSuccess();
    } catch (err) {
      setError(err.error_message || '批量处理失败');
    } finally {
      setProcessing(false);
    }
  };

  return (
    <div class="modal-overlay" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div class="modal">
        <div class="modal-header">
          <h3>批量{actionLabels[action] || action}</h3>
          <button class="close-btn" onClick={onClose}>&times;</button>
        </div>
        <div class="modal-body">
          {error() && <div class="error-message">{error()}</div>}

          <div class="detail-section">
            <h4>待处理申请（共 {applications.length} 条）</h4>
            <table class="table">
              <thead>
                <tr>
                  <th>申请编号</th>
                  <th>申请人</th>
                  <th>当前节点</th>
                  <th>当前状态</th>
                  <th>版本</th>
                </tr>
              </thead>
              <tbody>
                <For each={applications}>
                  {(app) => (
                    <tr>
                      <td>{app.application_no}</td>
                      <td>{app.applicant_name}</td>
                      <td>{app.current_node_name}</td>
                      <td>
                        <span class={`badge badge-${app.status}`}>{app.status_name}</span>
                      </td>
                      <td>v{app.version}</td>
                    </tr>
                  )}
                </For>
              </tbody>
            </table>
          </div>

          <div class="form-group">
            <label>处理意见（可选）</label>
            <textarea
              value={comment()}
              onInput={(e) => setComment(e.target.value)}
              placeholder="请输入统一处理意见"
            />
          </div>

          {results() && (
            <div class="batch-results">
              <h4 style={{ marginBottom: '12px' }}>
                处理结果：成功 {results().success_count} 条，失败 {results().failure_count} 条
              </h4>
              <For each={results().results}>
                {(result) => (
                  <div class={`batch-result-item ${result.success ? 'success' : 'failure'}`}>
                    <span>
                      <strong>{result.application_no}</strong>
                      {result.success ? ' - 处理成功' : ` - ${result.error_code}: ${result.error_message}`}
                    </span>
                    <span class={`badge badge-${result.success ? 'passed' : 'returned'}`}>
                      {result.success ? '成功' : '失败'}
                    </span>
                  </div>
                )}
              </For>
            </div>
          )}
        </div>
        <div class="modal-footer">
          {!results() && (
            <>
              <button class="btn btn-default" onClick={onClose} disabled={processing()}>
                取消
              </button>
              <button
                class="btn btn-primary"
                onClick={handleSubmit}
                disabled={processing()}
              >
                {processing() ? '处理中...' : `确认批量${actionLabels[action] || action}`}
              </button>
            </>
          )}
          {results() && (
            <button class="btn btn-primary" onClick={onClose}>
              关闭
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

// frontend/app/components/BatchProcessModal.tsx
import { useState } from 'react'
import { batchProcess } from '../lib/batch'
import { getErrorMessage } from '../lib/apiClient'

interface BatchProcessModalProps {
  items: any[]
  onClose: () => void
  onSuccess?: () => void
  currentRole: string
}

const ACTION_LABELS: Record<string, string> = {
  submit: '提交',
  supplement: '补正',
  process: '处理',
  review: '复核',
}

export default function BatchProcessModal({
  items,
  onClose,
  onSuccess,
  currentRole,
}: BatchProcessModalProps) {
  const [action, setAction] = useState('')
  const [remark, setRemark] = useState('')
  const [results, setResults] = useState<any[] | null>(null)
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const availableActions: { value: string; label: string }[] = []
  if (currentRole === 'CONSULTANT') {
    availableActions.push({ value: 'submit', label: '提交' })
    availableActions.push({ value: 'supplement', label: '补正' })
  } else if (currentRole === 'EVALUATOR') {
    availableActions.push({ value: 'process', label: '处理' })
  } else if (currentRole === 'MANAGER') {
    availableActions.push({ value: 'review', label: '复核' })
  }

  const handleSubmit = async () => {
    if (!action) return
    setError('')
    setLoading(true)
    try {
      const payload = items.map((item) => ({
        application_id: item.id,
        action,
        remark,
        status: item.status,
        version: item.version,
      }))
      const res = await batchProcess(payload)
      setResults(res.data)
      if (res.data.every((r: any) => r.success)) {
        onSuccess?.()
      }
    } catch (e) {
      setError(getErrorMessage(e))
    } finally {
      setLoading(false)
    }
  }

  const successCount = results
    ? results.filter((r) => r.success).length
    : 0
  const failCount = results ? results.filter((r) => !r.success).length : 0

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className="modal"
        style={{ maxWidth: 700 }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="modal-header">
          <span className="modal-title">批量处理车源上架单</span>
          <button className="modal-close" onClick={onClose}>
            &times;
          </button>
        </div>
        <div className="modal-body">
          {error && <div className="error-message">{error}</div>}
          <p style={{ marginBottom: 16, color: '#6b7280' }}>
            已选择 <strong>{items.length}</strong> 条上架单
          </p>
          {!results && (
            <>
              <div className="form-group">
                <label>操作类型 *</label>
                <select
                  value={action}
                  onChange={(e) => setAction(e.target.value)}
                >
                  <option value="">请选择</option>
                  {availableActions.map((a) => (
                    <option key={a.value} value={a.value}>
                      {a.label}
                    </option>
                  ))}
                </select>
              </div>
              <div className="form-group">
                <label>备注（可选）</label>
                <textarea
                  value={remark}
                  onChange={(e) => setRemark(e.target.value)}
                />
              </div>
            </>
          )}
          {results && (
            <div>
              {results.map((r, i) => (
                <div
                  key={i}
                  className={`batch-result-item ${r.success ? 'batch-result-success' : 'batch-result-failure'}`}
                >
                  <span>{r.success ? '✓' : '✗'}</span>
                  <span>{r.application_no}</span>
                  {r.reason && (
                    <span className="batch-result-reason">{r.reason}</span>
                  )}
                </div>
              ))}
              <div className="batch-summary">
                成功{' '}
                <span style={{ color: '#16a34a' }}>{successCount}</span>{' '}
                条，失败{' '}
                <span style={{ color: '#dc2626' }}>{failCount}</span>{' '}
                条
              </div>
            </div>
          )}
        </div>
        <div className="modal-footer">
          {results ? (
            <button className="btn-primary" onClick={onClose}>
              关闭
            </button>
          ) : (
            <>
              <button className="btn-outline" onClick={onClose}>
                取消
              </button>
              <button
                className="btn-primary"
                onClick={handleSubmit}
                disabled={!action || loading}
              >
                {loading ? '处理中...' : '确认处理'}
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  )
}
