// frontend/src/components/Layout.tsx
import { Component, createSignal, JSX } from 'solid-js';
import { A, useNavigate, useLocation } from '@solidjs/router';
import { user, logout, loginWithDemo } from '../store/auth';
import { getRoleLabel, DEMO_ACCOUNTS } from '../utils/role';
import type { UserRole } from '../types';

interface LayoutProps {
  children: JSX.Element;
}

const Layout: Component<LayoutProps> = (props) => {
  const navigate = useNavigate();
  const location = useLocation();
  const [showRoleMenu, setShowRoleMenu] = createSignal(false);
  const [showUserMenu, setShowUserMenu] = createSignal(false);

  const handleLogout = async () => {
    await logout();
    navigate('/login');
  };

  const handleSwitchRole = async (role: UserRole) => {
    const account = DEMO_ACCOUNTS.find((a) => a.role === role);
    if (account) {
      await loginWithDemo(role);
      navigate('/applications');
    }
    setShowRoleMenu(false);
  };

  const isActive = (path: string) => location.pathname.startsWith(path);

  const switchRoleStyle = {
    position: 'absolute' as const,
    top: '100%',
    right: 0,
    background: '#fff',
    border: '1px solid #e8e8e8',
    borderRadius: '4px',
    padding: '8px 0',
    marginTop: '4px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    zIndex: 100,
    minWidth: '180px',
  };

  const menuItemStyle = {
    padding: '8px 16px',
    cursor: 'pointer',
    fontSize: '14px',
  };

  return (
    <div style={{ minHeight: '100vh', display: 'flex', 'flex-direction': 'column' }}>
      <header
        style={{
          background: '#fff',
          height: '60px',
          padding: '0 24px',
          display: 'flex',
          'align-items': 'center',
          'justify-content': 'space-between',
          'box-shadow': '0 1px 4px rgba(0,0,0,0.08)',
          position: 'sticky',
          top: 0,
          zIndex: 10,
        }}
      >
        <div style={{ display: 'flex', 'align-items': 'center', gap: '48px' }}>
          <div
            style={{
              'font-size': '18px',
              'font-weight': '700',
              color: '#1890ff',
            }}
          >
            费用报销管理系统
          </div>
          <nav style={{ display: 'flex', gap: '8px' }}>
            <A
              href="/applications"
              style={{
                padding: '8px 16px',
                'border-radius': '4px',
                'font-size': '14px',
                color: isActive('/applications') ? '#1890ff' : '#666',
                background: isActive('/applications') ? '#e6f7ff' : 'transparent',
                'font-weight': isActive('/applications') ? '500' : 'normal',
              }}
            >
              申请列表
            </A>
            <A
              href="/batch"
              style={{
                padding: '8px 16px',
                'border-radius': '4px',
                'font-size': '14px',
                color: isActive('/batch') ? '#1890ff' : '#666',
                background: isActive('/batch') ? '#e6f7ff' : 'transparent',
                'font-weight': isActive('/batch') ? '500' : 'normal',
              }}
            >
              批量处理
            </A>
          </nav>
        </div>

        <div style={{ display: 'flex', 'align-items': 'center', gap: '16px' }}>
          {user() && (
            <>
              <div style={{ position: 'relative' }}>
                <button class="btn" onClick={() => setShowRoleMenu(!showRoleMenu())}>
                  切换角色
                </button>
                {showRoleMenu() && (
                  <div style={switchRoleStyle} onClick={() => setShowRoleMenu(false)}>
                    {DEMO_ACCOUNTS.map((account) => (
                      <div
                        style={{
                          ...menuItemStyle,
                          color: account.role === user()?.role ? '#1890ff' : '#333',
                          'font-weight': account.role === user()?.role ? '500' : 'normal',
                          background: account.role === user()?.role ? '#e6f7ff' : 'transparent',
                        }}
                        onClick={() => handleSwitchRole(account.role)}
                      >
                        {account.name}（{getRoleLabel(account.role)}）
                      </div>
                    ))}
                  </div>
                )}
              </div>

              <div style={{ position: 'relative' }}>
                <div
                  style={{
                    display: 'flex',
                    'align-items': 'center',
                    gap: '8px',
                    padding: '8px 12px',
                    cursor: 'pointer',
                    'border-radius': '4px',
                  }}
                  onClick={() => setShowUserMenu(!showUserMenu())}
                >
                  <div
                    style={{
                      width: '32px',
                      height: '32px',
                      'border-radius': '50%',
                      background: '#1890ff',
                      color: '#fff',
                      display: 'flex',
                      'align-items': 'center',
                      'justify-content': 'center',
                      'font-weight': '600',
                      'font-size': '14px',
                    }}
                  >
                    {user()?.real_name?.charAt(0)}
                  </div>
                  <div>
                    <div style={{ 'font-size': '14px', 'font-weight': '500', color: '#333' }}>
                      {user()?.real_name}
                    </div>
                    <div style={{ 'font-size': '12px', color: '#999' }}>
                      {getRoleLabel(user()?.role!)}
                    </div>
                  </div>
                </div>
                {showUserMenu() && (
                  <div style={switchRoleStyle}>
                    <div style={{ ...menuItemStyle, color: '#ff4d4f' }} onClick={handleLogout}>
                      退出登录
                    </div>
                  </div>
                )}
              </div>
            </>
          )}
        </div>
      </header>

      <main style={{ flex: 1 }}>{props.children}</main>
    </div>
  );
};

export default Layout;

// frontend/app/components/Layout.tsx
import { NavLink, useNavigate } from "@remix-run/react";
import type { UserRole } from "~/utils/auth";
import { getCurrentUser, logout, ROLE_LABELS, demoLogin } from "~/utils/auth";

const MENU_ITEMS = [
  { path: "/dashboard", label: "适当性记录队列", icon: "📋" },
  { path: "/batch", label: "批量处理", icon: "⚡" },
  { path: "/expiry", label: "到期预警", icon: "⏰" },
  { path: "/stats", label: "统计", icon: "📊" },
];

export default function Layout({ children }: { children: React.ReactNode }) {
  const navigate = useNavigate();
  const user = getCurrentUser();

  const handleLogout = () => {
    logout();
    navigate("/login");
  };

  const handleRoleSwitch = async (role: UserRole) => {
    try {
      await demoLogin(role);
      window.location.reload();
    } catch {
      alert("切换角色失败");
    }
  };

  return (
    <div style={{ display: "flex", minHeight: "100vh" }}>
      <aside style={sidebarStyle}>
        <div style={logoStyle}>
          <div style={logoIconStyle}>🏛</div>
          <div style={logoTextStyle}>
            <div style={logoTitleStyle}>适当性记录系统</div>
            <div style={logoSubStyle}>证券营业部管理</div>
          </div>
        </div>

        <nav style={navStyle}>
          {MENU_ITEMS.map((item) => (
            <NavLink
              key={item.path}
              to={item.path}
              style={({ isActive }) => ({
                ...navItemStyle,
                ...(isActive ? navItemActiveStyle : {}),
              })}
            >
              <span style={{ fontSize: 16 }}>{item.icon}</span>
              <span>{item.label}</span>
            </NavLink>
          ))}
        </nav>

        <div style={sidebarFooterStyle}>
          {user && (
            <>
              <div style={userInfoStyle}>
                <div style={userAvatarStyle}>
                  {user.name.charAt(0)}
                </div>
                <div>
                  <div style={{ fontWeight: 600, fontSize: 13 }}>{user.name}</div>
                  <div style={{ fontSize: 12, color: "var(--gray-400)" }}>
                    {ROLE_LABELS[user.role]}
                  </div>
                </div>
              </div>
              <div style={roleSwitchStyle}>
                <div style={{ fontSize: 11, color: "var(--gray-400)", marginBottom: 6 }}>
                  切换角色（演示）
                </div>
                <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
                  {(["financial_advisor", "compliance_officer", "branch_manager"] as UserRole[]).map(
                    (role) => (
                      <button
                        key={role}
                        onClick={() => handleRoleSwitch(role)}
                        style={{
                          ...roleBtnStyle,
                          ...(user.role === role ? roleBtnActiveStyle : {}),
                        }}
                      >
                        {ROLE_LABELS[role]}
                      </button>
                    )
                  )}
                </div>
              </div>
              <button onClick={handleLogout} style={logoutBtnStyle}>
                退出登录
              </button>
            </>
          )}
        </div>
      </aside>

      <main style={mainStyle}>
        {children}
      </main>
    </div>
  );
}

const sidebarStyle: React.CSSProperties = {
  width: 240,
  minWidth: 240,
  background: "#fff",
  borderRight: "1px solid var(--gray-200)",
  display: "flex",
  flexDirection: "column",
  boxShadow: "var(--shadow-sm)",
};

const logoStyle: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: 10,
  padding: "20px 16px",
  borderBottom: "1px solid var(--gray-200)",
};

const logoIconStyle: React.CSSProperties = {
  width: 36,
  height: 36,
  background: "var(--primary)",
  borderRadius: 8,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  fontSize: 20,
};

const logoTextStyle: React.CSSProperties = {
  display: "flex",
  flexDirection: "column",
};

const logoTitleStyle: React.CSSProperties = {
  fontWeight: 700,
  fontSize: 15,
  color: "var(--gray-800)",
  lineHeight: 1.2,
};

const logoSubStyle: React.CSSProperties = {
  fontSize: 11,
  color: "var(--gray-400)",
  lineHeight: 1.2,
};

const navStyle: React.CSSProperties = {
  flex: 1,
  padding: "12px 8px",
  display: "flex",
  flexDirection: "column",
  gap: 2,
};

const navItemStyle: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: 10,
  padding: "10px 12px",
  borderRadius: "var(--radius)",
  color: "var(--gray-600)",
  fontWeight: 500,
  fontSize: 14,
  textDecoration: "none",
  transition: "all 0.15s ease",
};

const navItemActiveStyle: React.CSSProperties = {
  background: "var(--primary-light)",
  color: "var(--primary)",
  fontWeight: 600,
};

const sidebarFooterStyle: React.CSSProperties = {
  padding: 16,
  borderTop: "1px solid var(--gray-200)",
};

const userInfoStyle: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: 10,
  marginBottom: 12,
};

const userAvatarStyle: React.CSSProperties = {
  width: 32,
  height: 32,
  borderRadius: "50%",
  background: "var(--primary)",
  color: "#fff",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  fontWeight: 600,
  fontSize: 14,
};

const roleSwitchStyle: React.CSSProperties = {
  marginBottom: 12,
};

const roleBtnStyle: React.CSSProperties = {
  padding: "3px 8px",
  fontSize: 11,
  borderRadius: 4,
  border: "1px solid var(--gray-300)",
  background: "#fff",
  color: "var(--gray-600)",
  cursor: "pointer",
};

const roleBtnActiveStyle: React.CSSProperties = {
  background: "var(--primary)",
  color: "#fff",
  borderColor: "var(--primary)",
};

const logoutBtnStyle: React.CSSProperties = {
  width: "100%",
  padding: "8px 0",
  border: "1px solid var(--gray-300)",
  borderRadius: "var(--radius)",
  background: "#fff",
  color: "var(--gray-600)",
  fontSize: 13,
  cursor: "pointer",
};

const mainStyle: React.CSSProperties = {
  flex: 1,
  overflow: "auto",
  padding: 24,
  background: "var(--gray-50)",
};
