// frontend/src/routes/warnings/+page.svelte
<script lang="ts">
	import { getExpiryWarnings, getExceptions, batchAdvanceOverdue } from '$lib/api';
	import { STATUS_LABELS, EXPIRY_LABELS, STATUS_COLORS, ROLE_LABELS } from '$lib/types';
	import type { Application, ExceptionReason, BatchResultItem } from '$lib/types';
	import { goto } from '$app/navigation';

	let warnings: Record<string, Application[]> = { normal: [], near_expiry: [], overdue: [] };
	let loading = true;
	let error = '';
	let activeSection = 'overdue';

	let exceptionMap: Record<number, ExceptionReason[]> = {};
	let showingExceptions: number | null = null;

	let selectedOverdueIds: number[] = [];
	let advancing = false;
	let advanceResults: BatchResultItem[] = [];
	let showAdvanceResults = false;

	async function loadData() {
		loading = true;
		error = '';
		try {
			warnings = await getExpiryWarnings();
		} catch (err: any) {
			error = err.code ? `${err.code}: ${err.message}` : '加载数据失败';
		}
		loading = false;
	}

	async function loadExceptions(appId: number) {
		if (showingExceptions === appId) {
			showingExceptions = null;
			return;
		}
		if (!exceptionMap[appId]) {
			try {
				exceptionMap[appId] = await getExceptions(appId);
			} catch {
				exceptionMap[appId] = [];
			}
		}
		showingExceptions = appId;
	}

	function toggleOverdue(id: number) {
		if (selectedOverdueIds.includes(id)) {
			selectedOverdueIds = selectedOverdueIds.filter(i => i !== id);
		} else {
			selectedOverdueIds = [...selectedOverdueIds, id];
		}
		selectedOverdueIds = selectedOverdueIds;
	}

	function toggleAllOverdue() {
		const overdue = warnings.overdue || [];
		if (selectedOverdueIds.length === overdue.length) {
			selectedOverdueIds = [];
		} else {
			selectedOverdueIds = overdue.map(a => a.id);
		}
		selectedOverdueIds = selectedOverdueIds;
	}

	async function handleBatchAdvance() {
		if (selectedOverdueIds.length === 0) return;
		advancing = true;
		error = '';
		showAdvanceResults = false;
		try {
			const res = await batchAdvanceOverdue(selectedOverdueIds);
			advanceResults = res.results || [];
			showAdvanceResults = true;
			exceptionMap = {};
			showingExceptions = null;
			selectedOverdueIds = [];
			loadData();
		} catch (err: any) {
			error = err.code ? `${err.code}: ${err.message}` : '批量推进失败';
		}
		advancing = false;
	}

	$: successCount = advanceResults.filter(r => r.success).length;
	$: failCount = advanceResults.filter(r => !r.success).length;

	$: normalApps = warnings.normal || [];
	$: nearExpiryApps = warnings.near_expiry || [];
	$: overdueApps = warnings.overdue || [];

	const sectionConfig = [
		{ key: 'normal', label: '正常', color: '#4caf50', apps: [] as Application[] },
		{ key: 'near_expiry', label: '临期', color: '#ff9800', apps: [] as Application[] },
		{ key: 'overdue', label: '逾期', color: '#f44336', apps: [] as Application[] }
	];

	import { onMount } from 'svelte';
	onMount(() => { loadData(); });
</script>

<svelte:head>
	<title>到期预警 - 冷链物流仓入库单系统</title>
</svelte:head>

<h2 class="page-title">到期预警</h2>

{#if error}
	<div class="error-msg">{error}</div>
{/if}

{#if showAdvanceResults}
	<div class="results-card">
		<h3 class="card-title">批量推进结果</h3>
		<div class="results-summary">
			<span class="success-count">✅ 成功: {successCount}</span>
			<span class="fail-count">❌ 失败: {failCount}</span>
		</div>
		<div class="result-list">
			{#each advanceResults as r, i}
				<div class="result-item {r.success ? 'success' : 'fail'}">
					<div class="result-header">
						<span class="result-index">#{i + 1}</span>
						<span class="result-order">{r.order_no}</span>
						<span class="badge small" style="background:{r.success ? '#4caf50' : '#f44336'}">{r.success ? '成功' : '失败'}</span>
						{#if r.error_code}
							<span class="badge small error-code" style="background:#ff9800">{r.error_code}</span>
						{/if}
					</div>
					{#if !r.success && r.reason}
						<div class="result-reason">{r.reason}</div>
					{/if}
				</div>
			{/each}
		</div>
	</div>
{/if}

{#if loading}
	<div class="loading">加载中...</div>
{:else}
	<div class="tabs">
		<button class="tab-btn" class:active={activeSection === 'normal'} on:click={() => activeSection = 'normal'}>正常 ({normalApps.length})</button>
		<button class="tab-btn" class:active={activeSection === 'near_expiry'} on:click={() => activeSection = 'near_expiry'}>临期 ({nearExpiryApps.length})</button>
		<button class="tab-btn" class:active={activeSection === 'overdue'} on:click={() => activeSection = 'overdue'}>逾期 ({overdueApps.length})</button>
	</div>

	<div class="tab-content">
		{#if activeSection === 'normal'}
			<div class="section-header" style="border-left-color: #4caf50">
				<h3>正常</h3>
			</div>
			{#if normalApps.length === 0}
				<div class="empty">暂无正常入库单</div>
			{:else}
				<table class="data-table">
					<thead><tr><th>单号</th><th>品名</th><th>数量</th><th>预计到期</th><th>状态</th><th>当前处理人</th></tr></thead>
					<tbody>
						{#each normalApps as app}
							<tr class="clickable" on:click={() => goto(`/applications/${app.id}`)}>
								<td>{app.order_no}</td>
								<td>{app.product_name}</td>
								<td>{app.product_count}</td>
								<td>{app.expected_date}</td>
								<td><span class="badge small" style="background:{STATUS_COLORS[app.status] || '#999'}">{STATUS_LABELS[app.status] || app.status}</span></td>
								<td>
									{#if app.status === 'draft' || app.status === 'pending_correction'}
										{app.creator_name || '-'}
									{:else if app.status === 'pending_temp'}
										{app.handler_name || '待分配'}
									{:else if app.status === 'under_review'}
										仓储经理
									{:else}
										-
									{/if}
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			{/if}
		{/if}

		{#if activeSection === 'near_expiry'}
			<div class="section-header" style="border-left-color: #ff9800">
				<h3>临期</h3>
			</div>
			{#if nearExpiryApps.length === 0}
				<div class="empty">暂无临期入库单</div>
			{:else}
				<table class="data-table">
					<thead><tr><th>单号</th><th>品名</th><th>数量</th><th>预计到期</th><th>状态</th><th>临期责任人</th><th>操作</th></tr></thead>
					<tbody>
						{#each nearExpiryApps as app}
							<tr>
								<td>{app.order_no}</td>
								<td>{app.product_name}</td>
								<td>{app.product_count}</td>
								<td>{app.expected_date}</td>
								<td><span class="badge small" style="background:{STATUS_COLORS[app.status] || '#999'}">{STATUS_LABELS[app.status] || app.status}</span></td>
								<td class="responsible">
									{#if app.status === 'draft' || app.status === 'pending_correction'}
										<span class="resp-name">{app.creator_name || '-'}</span>
										<span class="resp-role">仓管员</span>
									{:else if app.status === 'pending_temp'}
										<span class="resp-name">{app.handler_name || '待分配'}</span>
										<span class="resp-role">温控主管</span>
									{:else if app.status === 'under_review'}
										<span class="resp-name">仓储经理</span>
										<span class="resp-role">仓储经理</span>
									{:else}
										-
									{/if}
								</td>
								<td>
									<button class="btn-link" on:click={() => goto(`/applications/${app.id}`)}>补正动作</button>
									<button class="btn-link" on:click={() => loadExceptions(app.id)}>查看异常原因</button>
								</td>
							</tr>
							{#if showingExceptions === app.id && exceptionMap[app.id]}
								{#each exceptionMap[app.id] as ex}
									<tr class="sub-row">
										<td colspan="7">
											<span class="badge small" style="background:#f44336">{ex.reason_type}</span>
											{ex.description}
											<span class="meta">{ex.operator_name || '-'} | {ex.created_at}</span>
										</td>
									</tr>
								{/each}
							{/if}
						{/each}
					</tbody>
				</table>
			{/if}
		{/if}

		{#if activeSection === 'overdue'}
			<div class="section-header overdue-header" style="border-left-color: #f44336">
				<h3>🚨 逾期</h3>
				<span class="overdue-tip">以下单据已逾期，请立即推进或退回补正</span>
			</div>
			{#if overdueApps.length > 0}
				<div class="batch-bar">
					<label class="checkbox-label">
						<input type="checkbox" checked={selectedOverdueIds.length === overdueApps.length && overdueApps.length > 0} on:change={toggleAllOverdue} />
						全选
					</label>
					<button class="btn-danger" on:click={handleBatchAdvance} disabled={advancing || selectedOverdueIds.length === 0}>
						{advancing ? '推进中...' : `批量推进 (${selectedOverdueIds.length})`}
					</button>
				</div>
			{/if}
			{#if overdueApps.length === 0}
				<div class="empty">暂无逾期入库单</div>
			{:else}
				<table class="data-table overdue-table">
					<thead><tr><th></th><th>单号</th><th>品名</th><th>数量</th><th>预计到期</th><th>状态</th><th>⚠️ 逾期责任人</th><th>操作</th></tr></thead>
					<tbody>
						{#each overdueApps as app}
							<tr class="overdue-row">
								<td><input type="checkbox" checked={selectedOverdueIds.includes(app.id)} on:change={() => toggleOverdue(app.id)} /></td>
								<td class="order-no">{app.order_no}</td>
								<td>{app.product_name}</td>
								<td>{app.product_count}</td>
								<td class="expired-date">{app.expected_date}</td>
								<td><span class="badge small" style="background:{STATUS_COLORS[app.status] || '#999'}">{STATUS_LABELS[app.status] || app.status}</span></td>
								<td class="responsible overdue-resp">
									{#if app.status === 'draft' || app.status === 'pending_correction'}
										<span class="resp-name">{app.creator_name || '-'}</span>
										<span class="resp-role">{ROLE_LABELS.warehouse_clerk}</span>
									{:else if app.status === 'pending_temp'}
										<span class="resp-name">{app.handler_name || '待分配'}</span>
										<span class="resp-role">{ROLE_LABELS.temp_supervisor}</span>
									{:else if app.status === 'under_review'}
										<span class="resp-name">仓储经理</span>
										<span class="resp-role">{ROLE_LABELS.warehouse_manager}</span>
									{:else}
										-
									{/if}
								</td>
								<td>
									<button class="btn-link" on:click={() => goto(`/applications/${app.id}`)}>补正动作</button>
									<button class="btn-link" on:click={() => loadExceptions(app.id)}>查看异常原因</button>
								</td>
							</tr>
							{#if showingExceptions === app.id && exceptionMap[app.id]}
								{#each exceptionMap[app.id] as ex}
									<tr class="sub-row">
										<td colspan="8">
											<span class="badge small" style="background:#f44336">{ex.reason_type}</span>
											{ex.description}
											<span class="meta">{ex.operator_name || '-'} | {ex.created_at}</span>
										</td>
									</tr>
								{/each}
							{/if}
						{/each}
					</tbody>
				</table>
			{/if}
		{/if}
	</div>
{/if}

<style>
	.page-title {
		font-size: 20px;
		font-weight: 600;
		margin-bottom: 20px;
		color: var(--text);
	}
	.error-msg {
		background: #fff5f5;
		color: var(--danger);
		padding: 10px 14px;
		border-radius: 6px;
		margin-bottom: 16px;
		font-size: 13px;
		border: 1px solid #fed7d7;
	}
	.loading { text-align: center; padding: 40px; color: var(--text-light); }
	.results-card {
		background: var(--card-bg);
		border-radius: 8px;
		padding: 20px;
		box-shadow: var(--shadow);
		margin-bottom: 20px;
	}
	.card-title {
		font-size: 16px;
		font-weight: 600;
		margin-bottom: 12px;
		color: var(--text);
	}
	.results-summary {
		display: flex;
		gap: 20px;
		margin-bottom: 12px;
		font-size: 14px;
		font-weight: 500;
	}
	.success-count { color: var(--success); }
	.fail-count { color: var(--danger); }
	.tabs {
		display: flex;
		gap: 2px;
		border-bottom: 2px solid var(--border);
	}
	.tab-btn {
		padding: 10px 20px;
		background: none;
		border: none;
		font-size: 14px;
		color: var(--text-light);
		cursor: pointer;
		border-bottom: 2px solid transparent;
		margin-bottom: -2px;
	}
	.tab-btn:hover { color: var(--text); }
	.tab-btn.active {
		color: var(--primary);
		border-bottom-color: var(--primary);
		font-weight: 600;
	}
	.tab-content {
		background: var(--card-bg);
		border-radius: 0 0 8px 8px;
		padding: 20px;
		box-shadow: var(--shadow);
	}
	.section-header {
		border-left: 4px solid;
		padding-left: 12px;
		margin-bottom: 16px;
	}
	.section-header h3 {
		font-size: 16px;
		font-weight: 600;
		color: var(--text);
	}
	.data-table {
		width: 100%;
		border-collapse: collapse;
		font-size: 13px;
	}
	.data-table th {
		background: #f7fafc;
		padding: 10px 12px;
		text-align: left;
		font-weight: 600;
		border-bottom: 2px solid var(--border);
	}
	.data-table td {
		padding: 8px 12px;
		border-bottom: 1px solid var(--border);
	}
	.data-table tr.clickable { cursor: pointer; }
	.data-table tr.clickable:hover { background: #f0f7ff; }
	.data-table tr.sub-row td {
		background: #fef5f5;
		padding: 6px 12px;
		font-size: 12px;
		color: #666;
	}
	.data-table .empty {
		text-align: center;
		padding: 40px;
		color: var(--text-light);
	}
	.badge {
		display: inline-block;
		padding: 3px 10px;
		border-radius: 12px;
		color: white;
		font-size: 12px;
		font-weight: 500;
	}
	.badge.small { padding: 2px 8px; font-size: 11px; }
	.meta { font-size: 11px; color: var(--text-light); margin-left: 8px; }
	.btn-link {
		background: none;
		border: none;
		color: var(--accent);
		cursor: pointer;
		font-size: 12px;
		text-decoration: underline;
		margin-right: 8px;
	}
	.btn-link:hover { color: var(--primary); }
	.btn-danger {
		padding: 8px 20px;
		background: var(--danger);
		color: white;
		border: none;
		border-radius: 6px;
		font-size: 14px;
		cursor: pointer;
	}
	.btn-danger:hover:not(:disabled) { background: #e53935; }
	.btn-danger:disabled { opacity: 0.6; cursor: not-allowed; }
	.batch-bar {
		display: flex;
		align-items: center;
		gap: 16px;
		margin-bottom: 16px;
	}
	.checkbox-label {
		display: flex;
		align-items: center;
		gap: 6px;
		font-size: 13px;
		cursor: pointer;
	}
	.empty { text-align: center; padding: 40px; color: var(--text-light); }
	.responsible {
		display: flex;
		flex-direction: column;
		gap: 2px;
	}
	.resp-name {
		font-size: 13px;
		font-weight: 600;
		color: var(--text);
	}
	.resp-role {
		font-size: 11px;
		color: var(--text-light);
	}
	.overdue-resp .resp-name {
		color: var(--danger);
	}
	.overdue-header {
		display: flex;
		align-items: center;
		gap: 16px;
	}
	.overdue-header h3 {
		color: var(--danger);
	}
	.overdue-tip {
		font-size: 12px;
		color: var(--danger);
		font-weight: 500;
		background: #ffebee;
		padding: 4px 10px;
		border-radius: 12px;
	}
	.overdue-table {
		background: #fff8f8;
	}
	.overdue-row {
		background: #fff8f8;
	}
	.overdue-row:hover {
		background: #fff0f0 !important;
	}
	.overdue-row .order-no {
		font-weight: 600;
	}
	.overdue-row .expired-date {
		color: var(--danger);
		font-weight: 600;
	}
	.result-list {
		display: flex;
		flex-direction: column;
		gap: 10px;
		margin-top: 12px;
	}
	.result-item {
		border-radius: 8px;
		padding: 12px 16px;
		display: flex;
		flex-direction: column;
		gap: 6px;
	}
	.result-item.success {
		background: #f1f8e9;
		border-left: 4px solid #4caf50;
	}
	.result-item.fail {
		background: #fff8f8;
		border-left: 4px solid #f44336;
	}
	.result-header {
		display: flex;
		align-items: center;
		gap: 10px;
		flex-wrap: wrap;
	}
	.result-index {
		font-size: 12px;
		color: var(--text-light);
		font-weight: 600;
	}
	.result-order {
		font-size: 14px;
		font-weight: 600;
		color: var(--text);
	}
	.error-code {
		font-family: monospace;
		letter-spacing: 0.5px;
	}
	.result-reason {
		font-size: 13px;
		color: var(--text);
		padding-left: 2px;
		line-height: 1.5;
	}
</style>

// frontend/src/app/pages/warnings/warnings.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { OrderService, WarningResponse, TransportOrder, BatchResultItem } from '../../services/order.service';
import { AuthService } from '../../services/auth.service';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-warnings',
  standalone: true,
  imports: [CommonModule, RouterLink, FormsModule],
  template: `
    <div class="page-container">
      <div class="page-header">
        <h2 class="page-title">到期预警</h2>
      </div>

      <div class="stat-row">
        <div class="stat-card stat-normal">
          <div class="stat-num">{{ data()?.normal?.count || 0 }}</div>
          <div class="stat-label">正常</div>
        </div>
        <div class="stat-card stat-approaching">
          <div class="stat-num">{{ data()?.approaching?.count || 0 }}</div>
          <div class="stat-label">临期（3天内）</div>
        </div>
        <div class="stat-card stat-overdue">
          <div class="stat-num">{{ data()?.overdue?.count || 0 }}</div>
          <div class="stat-label">已逾期</div>
        </div>
      </div>

      <div class="tabs">
        <button class="tab-btn" [class.active]="activeTab === 'overdue'" (click)="activeTab = 'overdue'">
          已逾期 ({{ data()?.overdue?.count || 0 }})
        </button>
        <button class="tab-btn" [class.active]="activeTab === 'approaching'" (click)="activeTab = 'approaching'">
          临期 ({{ data()?.approaching?.count || 0 }})
        </button>
        <button class="tab-btn" [class.active]="activeTab === 'normal'" (click)="activeTab = 'normal'">
          正常 ({{ data()?.normal?.count || 0 }})
        </button>
      </div>

      <div class="card" *ngIf="activeGroup()">
        <div class="batch-bar" *ngIf="selectedIds().length > 0">
          <span>已选择 {{ selectedIds().length }} 条订单</span>
          <div class="batch-actions">
            <select [(ngModel)]="batchAction">
              <option value="通过">批量推进</option>
              <option value="退回补正">批量退回补正</option>
            </select>
            <button class="btn btn-primary btn-sm" (click)="doBatch()" [disabled]="batchLoading()">
              {{ batchLoading() ? '处理中...' : '执行' }}
            </button>
          </div>
        </div>

        <table class="data-table">
          <thead>
            <tr>
              <th style="width: 40px;">
                <input type="checkbox" [checked]="isAllSelected()" (change)="toggleAll()" />
              </th>
              <th>订单号</th>
              <th>状态</th>
              <th>优先级</th>
              <th>责任人</th>
              <th>当前处理人</th>
              <th>货物</th>
              <th>截止时间</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let o of activeGroup()?.orders">
              <td>
                <input type="checkbox"
                  [checked]="selectedIds().includes(o.id)"
                  (change)="toggleSelect(o)"
                  [disabled]="o.current_handler !== authService.currentUser()?.full_name" />
              </td>
              <td><a class="order-link" [routerLink]="['/orders', o.id]">{{ o.order_no }}</a></td>
              <td>
                <span class="status-tag" [ngClass]="getStatusClass(o)">
                  {{ o.is_overdue ? '逾期' : '' }}{{ o.status }}
                </span>
              </td>
              <td><span class="priority-{{ o.priority === '高' ? 'high' : o.priority === '中' ? 'medium' : 'low' }}">{{ o.priority }}</span></td>
              <td>{{ o.responsible_person }}</td>
              <td [class.handler-me]="o.current_handler === authService.currentUser()?.full_name">
                {{ o.current_handler }}
                <span *ngIf="o.current_handler === authService.currentUser()?.full_name" class="me-tag">（我）</span>
              </td>
              <td>{{ o.cargo_name || '-' }}</td>
              <td [class.overdue-text]="o.is_overdue">{{ formatDate(o.deadline) }}</td>
              <td><a class="btn-link" [routerLink]="['/orders', o.id]">补正</a></td>
            </tr>
            <tr *ngIf="!activeGroup()?.orders?.length">
              <td colspan="9" class="empty-cell">暂无订单</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="modal-overlay" *ngIf="showResultModal" (click.self)="showResultModal = false">
        <div class="modal-card modal-large">
          <div class="modal-header">
            <h3>批量处理结果</h3>
            <button class="btn-close" (click)="showResultModal = false">&times;</button>
          </div>
          <div class="modal-body">
            <div class="result-summary">
              <span class="result-success">成功 {{ results().filter(r => r.success).length }}</span>
              <span class="result-failed">失败 {{ results().filter(r => !r.success).length }}</span>
              <span class="result-total">共 {{ results().length }} 条</span>
            </div>
            <table class="data-table result-table">
              <thead>
                <tr>
                  <th>订单号</th>
                  <th>结果</th>
                  <th>失败原因（逐条）</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let r of results()">
                  <td>{{ r.order_no }}</td>
                  <td>
                    <span class="status-tag" [ngClass]="r.success ? 'status-completed' : 'status-overdue'">
                      {{ r.success ? '成功' : '失败' }}
                    </span>
                  </td>
                  <td>{{ r.message }}</td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="modal-footer">
            <button class="btn btn-primary" (click)="closeResult()">关闭</button>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .page-container { max-width: 1400px; margin: 0 auto; }
    .page-header { margin-bottom: 20px; }
    .page-title { font-size: 20px; font-weight: 600; }
    .stat-row { display: flex; gap: 16px; margin-bottom: 20px; }
    .stat-card { flex: 1; padding: 20px; border-radius: 6px; background: #fff; text-align: center; }
    .stat-normal { border-top: 3px solid #52c41a; }
    .stat-approaching { border-top: 3px solid #faad14; }
    .stat-overdue { border-top: 3px solid #ff4d4f; }
    .stat-num { font-size: 28px; font-weight: 700; }
    .stat-normal .stat-num { color: #389e0d; }
    .stat-approaching .stat-num { color: #d46b08; }
    .stat-overdue .stat-num { color: #cf1322; }
    .stat-label { font-size: 13px; color: #666; margin-top: 4px; }
    .tabs { display: flex; gap: 4px; margin-bottom: 16px; }
    .tab-btn {
      padding: 8px 20px; border: 1px solid #d9d9d9; background: #fff;
      border-radius: 4px 4px 0 0; font-size: 13px; cursor: pointer;
    }
    .tab-btn.active { background: #1677ff; color: #fff; border-color: #1677ff; }
    .card { background: #fff; border-radius: 6px; padding: 16px; box-shadow: 0 1px 2px rgba(0,0,0,0.03); }
    .batch-bar {
      display: flex; justify-content: space-between; align-items: center;
      padding: 10px 14px; background: #e6f4ff; border-radius: 4px; margin-bottom: 12px;
    }
    .batch-actions { display: flex; gap: 8px; align-items: center; }
    .batch-actions select { padding: 4px 8px; border: 1px solid #d9d9d9; border-radius: 4px; font-size: 12px; }
    .data-table { width: 100%; font-size: 13px; }
    .data-table th { background: #fafafa; padding: 10px 12px; text-align: left; border-bottom: 1px solid #f0f0f0; font-weight: 600; }
    .data-table td { padding: 10px 12px; border-bottom: 1px solid #f5f5f5; }
    .data-table tbody tr:hover { background: #fafafa; }
    .empty-cell { text-align: center; color: #999; padding: 40px !important; }
    .overdue-text { color: #cf1322; font-weight: 600; }
    .order-link { color: #1677ff; font-weight: 500; }
    .order-link:hover { text-decoration: underline; }
    .btn-link { color: #1677ff; }
    .btn-link:hover { text-decoration: underline; }
    .handler-me { color: #1677ff; font-weight: 600; }
    .me-tag { font-size: 12px; color: #1677ff; }
    .btn { padding: 6px 16px; border: 1px solid #d9d9d9; background: #fff; border-radius: 4px; font-size: 13px; cursor: pointer; }
    .btn:hover { border-color: #1677ff; color: #1677ff; }
    .btn-primary { background: #1677ff; color: #fff; border-color: #1677ff; }
    .btn-primary:hover { background: #4096ff; color: #fff; border-color: #4096ff; }
    .btn-primary:disabled { background: #91caff; cursor: not-allowed; color: #fff; border-color: #91caff; }
    .btn-sm { padding: 4px 12px; font-size: 12px; }
    .modal-overlay {
      position: fixed; inset: 0; background: rgba(0,0,0,0.45);
      display: flex; align-items: center; justify-content: center; z-index: 1000;
    }
    .modal-card { background: #fff; border-radius: 8px; width: 90%; max-width: 720px; max-height: 90vh; overflow: hidden; display: flex; flex-direction: column; }
    .modal-large { max-width: 800px; }
    .modal-header { display: flex; justify-content: space-between; align-items: center; padding: 16px 20px; border-bottom: 1px solid #f0f0f0; }
    .modal-header h3 { font-size: 16px; font-weight: 600; }
    .btn-close { background: none; border: none; font-size: 22px; cursor: pointer; color: #999; line-height: 1; }
    .modal-body { padding: 20px; overflow-y: auto; flex: 1; }
    .modal-footer { padding: 12px 20px; border-top: 1px solid #f0f0f0; display: flex; justify-content: flex-end; }
    .result-summary { display: flex; gap: 24px; margin-bottom: 16px; padding: 12px 16px; background: #fafafa; border-radius: 4px; }
    .result-success { color: #389e0d; font-weight: 600; }
    .result-failed { color: #cf1322; font-weight: 600; }
    .result-total { color: #666; }
    .result-table { margin-top: 8px; }
  `]
})
export class WarningsComponent implements OnInit {
  data = signal<WarningResponse | null>(null);
  activeTab: 'normal' | 'approaching' | 'overdue' = 'overdue';
  selectedIds = signal<number[]>([]);
  batchAction = '通过';
  batchLoading = signal(false);
  showResultModal = false;
  results = signal<BatchResultItem[]>([]);

  constructor(
    private orderService: OrderService,
    public authService: AuthService,
  ) {}

  ngOnInit() { this.loadData(); }

  loadData() {
    this.orderService.getWarnings().subscribe({
      next: d => { this.data.set(d); this.selectedIds.set([]); },
      error: err => console.error(err),
    });
  }

  activeGroup() {
    if (!this.data()) return null;
    switch (this.activeTab) {
      case 'normal': return this.data()!.normal;
      case 'approaching': return this.data()!.approaching;
      case 'overdue': return this.data()!.overdue;
    }
  }

  formatDate(s: string) {
    try { return new Date(s).toLocaleString('zh-CN'); } catch { return s; }
  }

  getStatusClass(o: TransportOrder): string {
    if (o.is_overdue) return 'status-overdue';
    if (o.status === '待补正') return 'status-pending';
    if (o.status === '复核中') return 'status-reviewing';
    return 'status-completed';
  }

  isAllSelected() {
    const list = this.activeGroup()?.orders || [];
    const mine = list.filter(o => o.current_handler === this.authService.currentUser()?.full_name);
    return mine.length > 0 && mine.every(o => this.selectedIds().includes(o.id));
  }

  toggleAll() {
    const list = this.activeGroup()?.orders || [];
    const mine = list.filter(o => o.current_handler === this.authService.currentUser()?.full_name);
    if (this.isAllSelected()) {
      this.selectedIds.set(this.selectedIds().filter(id => !mine.find(o => o.id === id)));
    } else {
      const ids = [...new Set([...this.selectedIds(), ...mine.map(o => o.id)])];
      this.selectedIds.set(ids);
    }
  }

  toggleSelect(o: TransportOrder) {
    const cur = this.selectedIds();
    if (cur.includes(o.id)) {
      this.selectedIds.set(cur.filter(id => id !== o.id));
    } else {
      this.selectedIds.set([...cur, o.id]);
    }
  }

  doBatch() {
    if (this.selectedIds().length === 0) return;
    this.batchLoading.set(true);
    this.orderService.batchProcess({
      order_ids: this.selectedIds(),
      action: this.batchAction,
    }).subscribe({
      next: res => {
        this.batchLoading.set(false);
        this.results.set(res.results);
        this.showResultModal = true;
        this.loadData();
      },
      error: err => {
        this.batchLoading.set(false);
        alert('批量处理失败：' + (err?.error?.detail || err?.message || '未知错误'));
      }
    });
  }

  closeResult() {
    this.showResultModal = false;
    this.results.set([]);
  }
}
