// frontend/src/views/Login.vue
<template>
  <div class="login-container">
    <div class="login-box">
      <div class="login-header">
        <h2>社区卫生服务中心</h2>
        <h3>慢病随访单管理系统</h3>
      </div>
      <el-form :model="form" :rules="rules" ref="formRef" class="login-form">
        <el-form-item prop="username">
          <el-input v-model="form.username" placeholder="请输入用户名" prefix-icon="User" />
        </el-form-item>
        <el-form-item prop="password">
          <el-input v-model="form.password" type="password" placeholder="请输入密码" prefix-icon="Lock" show-password />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" class="login-btn" @click="handleLogin" :loading="loading">登 录</el-button>
        </el-form-item>
      </el-form>
      <div class="demo-accounts">
        <p>演示账号：</p>
        <p>导诊护士：nurse1 / 123456</p>
        <p>全科医生：doctor1 / 123456</p>
        <p>医务科主任：director1 / 123456</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { useUserStore } from '../stores/user'

const router = useRouter()
const userStore = useUserStore()

const formRef = ref(null)
const loading = ref(false)
const form = reactive({
  username: '',
  password: ''
})

const rules = {
  username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
  password: [{ required: true, message: '请输入密码', trigger: 'blur' }]
}

async function handleLogin() {
  try {
    await formRef.value.validate()
    loading.value = true
    await userStore.login(form.username, form.password)
    ElMessage.success('登录成功')
    router.push('/')
  } catch (err) {
    console.error(err)
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.login-box {
  width: 400px;
  padding: 40px;
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.15);
}

.login-header {
  text-align: center;
  margin-bottom: 30px;
}

.login-header h2 {
  margin: 0 0 10px 0;
  color: #333;
  font-size: 22px;
}

.login-header h3 {
  margin: 0;
  color: #666;
  font-size: 16px;
  font-weight: normal;
}

.login-btn {
  width: 100%;
}

.demo-accounts {
  margin-top: 20px;
  padding: 15px;
  background: #f5f7fa;
  border-radius: 8px;
  font-size: 12px;
  color: #909399;
}

.demo-accounts p {
  margin: 4px 0;
}
</style>

// frontend/src/pages/Login.tsx
import { createSignal, Show } from 'solid-js';
import { useNavigate } from '@solidjs/router';
import { useAuth } from '@/context/AuthContext';
import { useToast } from '@/utils';
import type { Role } from '@/types';
import { RoleLabel } from '@/types';

const demoAccounts = [
  { role: 'doctor' as Role, username: 'doctor1', password: '123456', label: '口腔医生' },
  { role: 'consultant' as Role, username: 'consultant1', password: '123456', label: '前台顾问' },
  { role: 'dean' as Role, username: 'dean1', password: '123456', label: '门店院长' },
];

export default function Login() {
  const navigate = useNavigate();
  const { login } = useAuth();
  const { toast, show } = useToast();
  const [role, setRole] = useState<Role>('doctor');
  const [username, setUsername] = useState('doctor1');
  const [password, setPassword] = useState('123456');
  const [loading, setLoading] = useState(false);

  const handleRoleChange = (e: Event) => {
    const v = (e.target as HTMLSelectElement).value as Role;
    setRole(v);
    const acc = demoAccounts.find((a) => a.role === v);
    if (acc) {
      setUsername(acc.username);
      setPassword(acc.password);
    }
  };

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    if (!username || !password) {
      show('error', '请输入账号和密码');
      return;
    }
    setLoading(true);
    try {
      await login(role, username, password);
      show('success', '登录成功');
      setTimeout(() => navigate('/plans'), 300);
    } catch (err: any) {
      show('error', err.message || '登录失败');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      style={{
        width: '100%',
        height: '100vh',
        display: 'flex',
        align: 'center',
        'justify-content': 'center',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      }}
    >
      <div
        style={{
          background: '#fff',
          padding: '40px 48px',
          'border-radius': '12px',
          width: '420px',
          'box-shadow': '0 10px 40px rgba(0,0,0,0.15)',
        }}
      >
        <h1
          style={{
            'text-align': 'center',
            'font-size': '20px',
            color: '#333',
            'margin-bottom': '8px',
          }}
        >
          口腔连锁门诊
        </h1>
        <h2
          style={{
            'text-align': 'center',
            'font-size': '16px',
            color: '#666',
            'margin-bottom': '32px',
            'font-weight': 'normal',
          }}
        >
          月底集中处理治疗计划单系统
        </h2>
        <form onSubmit={handleSubmit}>
          <div class="form-item">
            <label class="form-label">选择角色</label>
            <select
              class="form-select"
              value={role}
              onChange={handleRoleChange}
            >
              {Object.entries(RoleLabel).map(([k, v]) => (
                <option value={k}>{v}</option>
              ))}
            </select>
          </div>
          <div class="form-item">
            <label class="form-label">账号</label>
            <input
              class="form-input"
              type="text"
              value={username}
              onInput={(e) => setUsername((e.target as HTMLInputElement).value)}
              placeholder="请输入账号"
            />
          </div>
          <div class="form-item">
            <label class="form-label">密码</label>
            <input
              class="form-input"
              type="password"
              value={password}
              onInput={(e) => setPassword((e.target as HTMLInputElement).value)}
              placeholder="请输入密码"
            />
          </div>
          <button
            type="submit"
            class="btn btn-primary"
            style={{ width: '100%', height: '42px', 'margin-top': '8px' }}
            disabled={loading()}
          >
            {loading() ? '登录中...' : '登 录'}
          </button>
        </form>

        <div
          style={{
            'margin-top': '24px',
            padding: '12px',
            background: '#f5f7fa',
            'border-radius': '6px',
            'font-size': '12px',
            color: '#666',
          }}
        >
          <div style={{ 'font-weight': '600', 'margin-bottom': '8px' }}>
            演示账号：
          </div>
          {demoAccounts.map((acc) => (
            <div style={{ 'margin-bottom': '4px' }}>
              {acc.label}：{acc.username} / {acc.password}
            </div>
          ))}
        </div>
      </div>

      <Show when={toast()}>
        <div class={`toast toast-${toast()!.type}`}>{toast()!.message}</div>
      </Show>
    </div>
  );
}
