// frontend/src/components/Login.jsx
import { createSignal } from 'solid-js';
import { api, setAuthCredentials } from '../api';

export default function Login({ onLogin }) {
  const [username, setUsername] = createSignal('');
  const [password, setPassword] = createSignal('');
  const [error, setError] = createSignal('');
  const [loading, setLoading] = createSignal(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      setAuthCredentials(username(), password());
      const user = await api.login(username(), password());
      onLogin(user);
    } catch (err) {
      setError(err.error_message || '登录失败，请检查用户名和密码');
      setAuthCredentials('', '');
    } finally {
      setLoading(false);
    }
  };

  const demoAccounts = [
    { username: 'community_worker', role: '社区专干', desc: '创建和补正申请' },
    { username: 'street_clerk', role: '街道科员', desc: '处理申请' },
    { username: 'leader', role: '分管领导', desc: '复核申请' },
  ];

  const quickLogin = async (account) => {
    setUsername(account.username);
    setPassword('demo123456');
    setError('');
    setLoading(true);

    try {
      setAuthCredentials(account.username, 'demo123456');
      const user = await api.login(account.username, 'demo123456');
      onLogin(user);
    } catch (err) {
      setError(err.error_message || '登录失败');
      setAuthCredentials('', '');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="login-container">
      <div class="login-card">
        <h2>街道办事处-月底集中处理帮扶申请系统</h2>

        {error() && <div class="error-message">{error()}</div>}

        <form onSubmit={handleSubmit}>
          <div class="form-group">
            <label>用户名</label>
            <input
              type="text"
              value={username()}
              onInput={(e) => setUsername(e.target.value)}
              placeholder="请输入用户名"
              required
            />
          </div>

          <div class="form-group">
            <label>密码</label>
            <input
              type="password"
              value={password()}
              onInput={(e) => setPassword(e.target.value)}
              placeholder="请输入密码"
              required
            />
          </div>

          <button
            type="submit"
            class="btn btn-primary"
            style={{ width: '100%', padding: '12px', fontSize: '16px' }}
            disabled={loading()}
          >
            {loading() ? '登录中...' : '登 录'}
          </button>
        </form>

        <div style={{ marginTop: '24px' }}>
          <p style={{ fontSize: '14px', color: '#8c8c8c', marginBottom: '12px' }}>演示账号（密码均为 demo123456）：</p>
          {demoAccounts.map((account) => (
            <button
              key={account.username}
              type="button"
              class="btn btn-default"
              style={{ width: '100%', marginBottom: '8px', textAlign: 'left' }}
              onClick={() => quickLogin(account)}
              disabled={loading()}
            >
              <strong>{account.role}</strong> - {account.username}
              <span style={{ color: '#8c8c8c', fontSize: '12px', marginLeft: '8px' }}>
                {account.desc}
              </span>
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

// frontend/src/pages/Login.jsx
import { h, useState } from 'preact';
import { useNavigate } from 'react-router-dom';
import api, { setToken, setUser } from '../api.js';

const DEMO_ACCOUNTS = [
  { username: 'registrar', password: '123456', name: '李登记', role: '晨检登记员' },
  { username: 'supervisor', password: '123456', name: '王主管', role: '晨检审核主管' },
  { username: 'principal', password: '123456', name: '张园长', role: '幼儿园复核负责人' }
];

export default function Login({ setUser, showToast }) {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const doLogin = async (u, p) => {
    setLoading(true);
    setError('');
    try {
      const res = await api.login(u, p);
      setToken(res.token);
      setUser(res.user);
      showToast(`欢迎，${res.user.name}`, 'success');
      navigate('/', { replace: true });
    } catch (err) {
      setError(err.message || '登录失败');
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!username || !password) {
      setError('请输入用户名和密码');
      return;
    }
    doLogin(username, password);
  };

  const handleDemoLogin = (acc) => {
    setUsername(acc.username);
    setPassword(acc.password);
    doLogin(acc.username, acc.password);
  };

  return (
    <div class="login-page">
      <div class="login-card">
        <h2>晨检记录系统</h2>
        <div class="subtitle">幼儿园月底集中处理平台</div>
        <form onSubmit={handleSubmit}>
          <div class="form-group">
            <label>用户名</label>
            <input
              type="text"
              value={username}
              onInput={(e) => setUsername(e.target.value)}
              placeholder="请输入用户名"
              autoComplete="username"
            />
          </div>
          <div class="form-group">
            <label>密码</label>
            <input
              type="password"
              value={password}
              onInput={(e) => setPassword(e.target.value)}
              placeholder="请输入密码"
              autoComplete="current-password"
            />
          </div>
          {error && <div class="error">{error}</div>}
          <button type="submit" disabled={loading}>
            {loading ? '登录中...' : '登录'}
          </button>
        </form>
        <div class="demo-accounts">
          <h4>演示账号（点击快速登录）：</h4>
          <ul>
            {DEMO_ACCOUNTS.map(acc => (
              <li key={acc.username}>
                <strong>{acc.role}</strong> — {acc.name}（{acc.username} / {acc.password}）
                <button type="button" onClick={() => handleDemoLogin(acc)}>登录</button>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}
