// frontend/app/routes/batch.tsx
import { Component, createSignal, For, Show, onMount } from 'solid-js';
import Layout from '~/components/Layout';
import StatusBadge from '~/components/StatusBadge';
import WarningTag from '~/components/WarningTag';
import BatchResultComponent from '~/components/BatchResult';
import FormModal from '~/components/FormModal';
import { getApplications, batchProcess } from '~/api/applications';
import { user, fetchMe } from '~/store/auth';
import {
  getAllowedActions,
  ACTION_LABELS,
  STATUS_GROUPS,
  GROUP_LABELS,
  getActionButtonClass,
} from '~/utils/status';
import type {
  Application,
  ProcessAction,
  BatchResultItem,
  BatchProcessItem,
  StatusGroup,
} from '~/types';
import dayjs from 'dayjs';

const BatchCenter: Component = () => {
  const [applications, setApplications] = createSignal<Application[]>([]);
  const [loading, setLoading] = createSignal(false);
  const [processing, setProcessing] = createSignal(false);
  const [selectedIds, setSelectedIds] = createSignal<Set<number>>(new Set());
  const [filterStatus, setFilterStatus] = createSignal<StatusGroup>('pending');
  const [keyword, setKeyword] = createSignal('');
  const [selectedAction, setSelectedAction] = createSignal<ProcessAction>('confirm');
  const [showResult, setShowResult] = createSignal(false);
  const [batchResults, setBatchResults] = createSignal<BatchResultItem[]>([]);
  const [modalOpen, setModalOpen] = createSignal(false);
  const [error, setError] = createSignal('');

  const loadData = async () => {
    if (!user()) {
      await fetchMe();
    }

    setLoading(true);
    setError('');
    try {
      const res = await getApplications({ page: 1, page_size: 200 });
      setApplications(res.list);
    } catch (err: any) {
      setError(err.message || '加载失败');
    } finally {
      setLoading(false);
    }
  };

  onMount(() => {
    loadData();
  });

  const filteredApplications = () => {
    let list = applications();

    if (filterStatus() !== 'all') {
      const groupStatuses = STATUS_GROUPS[filterStatus()];
      if (groupStatuses) {
        list = list.filter((a) => groupStatuses.includes(a.status));
      }
    }

    if (keyword()) {
      const kw = keyword().toLowerCase();
      list = list.filter(
        (a) =>
          a.application_no.toLowerCase().includes(kw) ||
          a.applicant_name.toLowerCase().includes(kw)
      );
    }

    return list;
  };

  const availableActions = (): ProcessAction[] => {
    if (!user()) return [];
    const actions = new Set<ProcessAction>();
    const selectedApps = filteredApplications().filter((a) => selectedIds().has(a.id));
    for (const app of selectedApps) {
      const allowed = getAllowedActions(app.status, user()!.role);
      for (const action of allowed) {
        actions.add(action);
      }
    }
    return Array.from(actions);
  };

  const toggleSelect = (id: number) => {
    const newSet = new Set(selectedIds());
    if (newSet.has(id)) {
      newSet.delete(id);
    } else {
      newSet.add(id);
    }
    setSelectedIds(newSet);
  };

  const toggleSelectAll = () => {
    const visibleIds = filteredApplications().map((a) => a.id);
    const allSelected = visibleIds.every((id) => selectedIds().has(id));
    if (allSelected) {
      setSelectedIds(new Set());
    } else {
      setSelectedIds(new Set(visibleIds));
    }
  };

  const isAllSelected = () => {
    const visibleIds = filteredApplications().map((a) => a.id);
    return visibleIds.length > 0 && visibleIds.every((id) => selectedIds().has(id));
  };

  const selectedApplications = () =>
    filteredApplications().filter((a) => selectedIds().has(a.id));

  const openBatchModal = (action: ProcessAction) => {
    setSelectedAction(action);
    setModalOpen(true);
  };

  const handleBatchProcess = async (payload: {
    comment?: string;
    reason_code?: string;
    reason_detail?: string;
    payment_evidence?: string;
    overdue_note?: string;
  }) => {
    const apps = selectedApplications();
    const items: BatchProcessItem[] = apps.map((app) => ({
      id: app.id,
      action: selectedAction(),
      version: app.version,
      ...payload,
    }));

    setProcessing(true);
    setError('');
    try {
      const res = await batchProcess({ items });
      setBatchResults(res.results);
      setShowResult(true);
      setModalOpen(false);
      setSelectedIds(new Set());
      await loadData();
    } catch (err: any) {
      setError(err.message || '批量处理失败');
    } finally {
      setProcessing(false);
    }
  };

  const tabs: StatusGroup[] = ['pending', 'exception', 'completed', 'all'];

  return (
    <Layout>
      <div class="container">
        <div class="card" style={{ marginBottom: '16px' }}>
          <div
            style={{
              display: 'flex',
              'justify-content': 'space-between',
              'align-items': 'center',
              marginBottom: '16px',
              'flex-wrap': 'wrap',
              gap: '12px',
            }}
          >
            <h2 style={{ 'font-size': '20px', 'font-weight': '600', margin: 0 }}>
              批量处理中心
            </h2>
            <div style={{ color: '#999', 'font-size': '14px' }}>
              已选择{' '}
              <span style={{ color: '#1890ff', 'font-weight': '600' }}>
                {selectedIds().size}
              </span>{' '}
              条申请
            </div>
          </div>

          <div class="tabs" style={{ marginBottom: '16px' }}>
            <For each={tabs}>
              {(tab) => (
                <div
                  class={{ 'tab-item': true, 'active': filterStatus() === tab }}
                  onClick={() => {
                    setFilterStatus(tab);
                    setSelectedIds(new Set());
                  }}
                >
                  {GROUP_LABELS[tab]}
                </div>
              )}
            </For>
          </div>

          <div class="filter-bar">
            <input
              type="text"
              class="form-input"
              style={{ width: '240px' }}
              placeholder="搜索编号/申请人"
              value={keyword()}
              onInput={(e) => setKeyword(e.target.value)}
            />
            <button class="btn" onClick={loadData}>
              刷新
            </button>
          </div>

          <Show when={error()}>
            <div
              style={{
                padding: '12px 16px',
                background: '#fff1f0',
                border: '1px solid #ffa39e',
                color: '#ff4d4f',
                'border-radius': '4px',
                marginBottom: '16px',
                'font-size': '14px',
              }}
            >
              {error()}
              <button
                class="btn btn-primary"
                style={{ 'margin-left': '16px' }}
                onClick={loadData}
              >
                重试
              </button>
            </div>
          </Show>

          <Show when={selectedIds().size > 0}>
            <div
              style={{
                padding: '16px',
                background: '#e6f7ff',
                'border-radius': '8px',
                border: '1px solid #91d5ff',
                marginBottom: '16px',
              }}
            >
              <div
                style={{
                  display: 'flex',
                  'align-items': 'center',
                  'justify-content': 'space-between',
                  'flex-wrap': 'wrap',
                  gap: '12px',
                }}
              >
                <div style={{ color: '#1890ff', 'font-weight': '500' }}>
                  已选择 {selectedIds().size} 条申请，请选择操作：
                </div>
                <div style={{ display: 'flex', gap: '8px', 'flex-wrap': 'wrap' }}>
                  <Show when={availableActions().length === 0}>
                    <span
                      style={{
                        color: '#999',
                        'font-size': '14px',
                        padding: '8px 0',
                      }}
                    >
                      所选申请无共同可用操作，请调整选择
                    </span>
                  </Show>
                  <For each={availableActions()}>
                    {(action) => (
                      <button
                        class={getActionButtonClass(action)}
                        onClick={() => openBatchModal(action)}
                      >
                        批量{ACTION_LABELS[action]}
                      </button>
                    )}
                  </For>
                </div>
              </div>
            </div>
          </Show>

          <div
            style={{
              overflow: 'auto',
              border: '1px solid #f0f0f0',
              'border-radius': '8px',
            }}
          >
            <table>
              <thead>
                <tr>
                  <th style={{ width: '48px' }}>
                    <input
                      type="checkbox"
                      checked={isAllSelected()}
                      style={{
                        cursor: 'pointer',
                        width: '16px',
                        height: '16px',
                      }}
                      onChange={toggleSelectAll}
                    />
                  </th>
                  <th>申请编号</th>
                  <th>申请人</th>
                  <th>标题</th>
                  <th>类型</th>
                  <th>金额</th>
                  <th>创建时间</th>
                  <th>到期日</th>
                  <th>状态</th>
                  <th>预警</th>
                </tr>
              </thead>
              <tbody>
                <Show when={loading()}>
                  <tr>
                    <td
                      colspan="10"
                      style={{
                        'text-align': 'center',
                        padding: '48px',
                        color: '#999',
                      }}
                    >
                      加载中...
                    </td>
                  </tr>
                </Show>
                <Show when={!loading() && filteredApplications().length === 0}>
                  <tr>
                    <td
                      colspan="10"
                      style={{
                        'text-align': 'center',
                        padding: '48px',
                        color: '#999',
                      }}
                    >
                      暂无数据
                    </td>
                  </tr>
                </Show>
                <For each={filteredApplications()}>
                  {(app) => (
                    <tr
                      style={{
                        background: selectedIds().has(app.id)
                          ? '#f0f8ff'
                          : undefined,
                      }}
                    >
                      <td>
                        <input
                          type="checkbox"
                          checked={selectedIds().has(app.id)}
                          style={{
                            cursor: 'pointer',
                            width: '16px',
                            height: '16px',
                          }}
                          onChange={() => toggleSelect(app.id)}
                        />
                      </td>
                      <td style={{ color: '#1890ff' }}>{app.application_no}</td>
                      <td>{app.applicant_name}</td>
                      <td
                        style={{
                          maxWidth: '200px',
                          overflow: 'hidden',
                          'text-overflow': 'ellipsis',
                          'white-space': 'nowrap',
                        }}
                        title={app.title}
                      >
                        {app.title}
                      </td>
                      <td>{app.type}</td>
                      <td style={{ color: '#f5222d', 'font-weight': '500' }}>
                        ¥
                        {app.amount.toLocaleString('zh-CN', {
                          minimumFractionDigits: 2,
                        })}
                      </td>
                      <td style={{ color: '#666', 'font-size': '13px' }}>
                        {dayjs(app.created_at).format('YYYY-MM-DD HH:mm')}
                      </td>
                      <td style={{ color: '#666', 'font-size': '13px' }}>
                        {dayjs(app.due_date).format('YYYY-MM-DD')}
                      </td>
                      <td>
                        <StatusBadge status={app.status} />
                      </td>
                      <td>
                        <WarningTag
                          dueDate={app.due_date}
                          isOverdue={app.is_overdue}
                        />
                      </td>
                    </tr>
                  )}
                </For>
              </tbody>
            </table>
          </div>
        </div>

        <Show when={showResult()}>
          <div class="card">
            <div
              style={{
                display: 'flex',
                'justify-content': 'space-between',
                'align-items': 'center',
                marginBottom: '16px',
              }}
            >
              <h3 style={{ 'font-size': '16px', 'font-weight': '600', margin: 0 }}>
                批量处理结果
              </h3>
              <button class="btn" onClick={() => setShowResult(false)}>
                关闭
              </button>
            </div>
            <BatchResultComponent results={batchResults()} />
          </div>
        </Show>
      </div>

      <FormModal
        open={modalOpen()}
        action={selectedAction()}
        isOverdue={selectedApplications().some((a) => a.is_overdue)}
        onClose={() => setModalOpen(false)}
        onConfirm={handleBatchProcess}
        loading={processing()}
      />
    </Layout>
  );
};

export default BatchCenter;

// frontend/src/routes/batch/+page.svelte
<script lang="ts">
	import { listApplications, batchProcess } from '$lib/api';
	import { STATUS_LABELS, TEMP_ZONE_LABELS } from '$lib/types';
	import type { Application, BatchResultItem } from '$lib/types';

	let applications: Application[] = [];
	let loading = true;
	let error = '';
	let selectedAction = 'submit';
	let selectedIds: number[] = [];
	let allocateZone = '';
	let returnRemark = '';

	let processing = false;
	let batchResults: BatchResultItem[] = [];
	let showResults = false;

	const actionOptions = [
		{ value: 'submit', label: '批量提交' },
		{ value: 'allocate', label: '批量分配' },
		{ value: 'confirm', label: '批量确认' },
		{ value: 'return', label: '批量退回' },
		{ value: 'correct', label: '批量修正' }
	];

	const statusFilterMap: Record<string, string> = {
		submit: 'draft',
		allocate: 'pending_temp',
		confirm: 'under_review',
		return: 'pending_temp',
		correct: 'pending_correction'
	};

	async function loadData() {
		loading = true;
		error = '';
		selectedIds = [];
		showResults = false;
		batchResults = [];
		try {
			const status = statusFilterMap[selectedAction];
			applications = await listApplications({ status });
		} catch (err: any) {
			error = err.code ? `${err.code}: ${err.message}` : '加载数据失败';
		}
		loading = false;
	}

	function toggleSelect(id: number) {
		if (selectedIds.includes(id)) {
			selectedIds = selectedIds.filter(i => i !== id);
		} else {
			selectedIds = [...selectedIds, id];
		}
		selectedIds = selectedIds;
	}

	function toggleAll() {
		if (selectedIds.length === applications.length) {
			selectedIds = [];
		} else {
			selectedIds = applications.map(a => a.id);
		}
		selectedIds = selectedIds;
	}

	async function handleBatchProcess() {
		if (selectedIds.length === 0) return;
		processing = true;
		error = '';
		showResults = false;
		try {
			const res = await batchProcess(
				selectedIds,
				selectedAction,
				selectedAction === 'return' ? returnRemark : undefined,
				selectedAction === 'allocate' ? allocateZone : undefined
			);
			batchResults = res.results || [];
			showResults = true;
			loadData();
		} catch (err: any) {
			error = err.code ? `${err.code}: ${err.message}` : '批量处理失败';
		}
		processing = false;
	}

	$: successCount = batchResults.filter(r => r.success).length;
	$: failCount = batchResults.filter(r => !r.success).length;

	import { onMount } from 'svelte';
	onMount(() => { loadData(); });
</script>

<svelte:head>
	<title>批量处理 - 冷链物流仓入库单系统</title>
</svelte:head>

<h2 class="page-title">批量处理</h2>

<div class="action-bar">
	<div class="action-left">
		<select bind:value={selectedAction} on:change={loadData}>
			{#each actionOptions as opt}
				<option value={opt.value}>{opt.label}</option>
			{/each}
		</select>
		{#if selectedAction === 'allocate'}
			<select bind:value={allocateZone}>
				<option value="">选择温区</option>
				{#each Object.entries(TEMP_ZONE_LABELS) as [key, label]}
					<option value={key}>{label}</option>
				{/each}
			</select>
		{/if}
		{#if selectedAction === 'return'}
			<input type="text" bind:value={returnRemark} placeholder="退回原因..." />
		{/if}
	</div>
	<button class="btn-primary" on:click={handleBatchProcess} disabled={processing || selectedIds.length === 0}>
		{processing ? '处理中...' : `批量处理 (${selectedIds.length})`}
	</button>
</div>

{#if error}
	<div class="error-msg">{error}</div>
{/if}

{#if showResults}
	<div class="results-card">
		<h3 class="card-title">处理结果</h3>
		<div class="results-summary">
			<span class="success-count">成功: {successCount}</span>
			<span class="fail-count">失败: {failCount}</span>
		</div>
		<table class="data-table">
			<thead><tr><th>单号</th><th>结果</th><th>原因</th></tr></thead>
			<tbody>
				{#each batchResults as r}
					<tr>
						<td>{r.order_no}</td>
						<td>{r.success ? '✅' : '❌'}</td>
						<td>{r.reason || '-'}</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
{/if}

{#if loading}
	<div class="loading">加载中...</div>
{:else}
	<div class="table-wrap">
		<table class="data-table">
			<thead>
				<tr>
					<th><input type="checkbox" checked={selectedIds.length === applications.length && applications.length > 0} on:change={toggleAll} /></th>
					<th>单号</th>
					<th>品名</th>
					<th>数量</th>
					<th>预计到期</th>
					<th>状态</th>
				</tr>
			</thead>
			<tbody>
				{#if applications.length === 0}
					<tr><td colspan="6" class="empty">暂无符合条件的入库单</td></tr>
				{/if}
				{#each applications as app}
					<tr>
						<td><input type="checkbox" checked={selectedIds.includes(app.id)} on:change={() => toggleSelect(app.id)} /></td>
						<td>{app.order_no}</td>
						<td>{app.product_name}</td>
						<td>{app.product_count}</td>
						<td>{app.expected_date}</td>
						<td>{STATUS_LABELS[app.status] || app.status}</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
{/if}

<style>
	.page-title {
		font-size: 20px;
		font-weight: 600;
		margin-bottom: 20px;
		color: var(--text);
	}
	.action-bar {
		display: flex;
		align-items: center;
		justify-content: space-between;
		margin-bottom: 20px;
		gap: 12px;
		flex-wrap: wrap;
	}
	.action-left {
		display: flex;
		gap: 10px;
		align-items: center;
		flex-wrap: wrap;
	}
	.action-left select, .action-left input {
		padding: 8px 12px;
		border: 1px solid var(--border);
		border-radius: 6px;
		font-size: 13px;
		background: var(--card-bg);
	}
	.action-left input { width: 200px; }
	.btn-primary {
		padding: 8px 20px;
		background: var(--primary);
		color: white;
		border: none;
		border-radius: 6px;
		font-size: 14px;
		cursor: pointer;
		white-space: nowrap;
	}
	.btn-primary:hover:not(:disabled) { background: var(--primary-light); }
	.btn-primary:disabled { opacity: 0.6; cursor: not-allowed; }
	.error-msg {
		background: #fff5f5;
		color: var(--danger);
		padding: 10px 14px;
		border-radius: 6px;
		margin-bottom: 16px;
		font-size: 13px;
		border: 1px solid #fed7d7;
	}
	.loading { text-align: center; padding: 40px; color: var(--text-light); }
	.results-card {
		background: var(--card-bg);
		border-radius: 8px;
		padding: 20px;
		box-shadow: var(--shadow);
		margin-bottom: 20px;
	}
	.card-title {
		font-size: 16px;
		font-weight: 600;
		margin-bottom: 12px;
		color: var(--text);
	}
	.results-summary {
		display: flex;
		gap: 20px;
		margin-bottom: 12px;
		font-size: 14px;
		font-weight: 500;
	}
	.success-count { color: var(--success); }
	.fail-count { color: var(--danger); }
	.table-wrap {
		overflow-x: auto;
		background: var(--card-bg);
		border-radius: 8px;
		box-shadow: var(--shadow);
	}
	.data-table {
		width: 100%;
		border-collapse: collapse;
		font-size: 13px;
	}
	.data-table th {
		background: #f7fafc;
		padding: 10px 14px;
		text-align: left;
		font-weight: 600;
		border-bottom: 2px solid var(--border);
	}
	.data-table td {
		padding: 8px 14px;
		border-bottom: 1px solid var(--border);
	}
	.data-table .empty {
		text-align: center;
		padding: 40px;
		color: var(--text-light);
	}
</style>
