// frontend/src/routes/login/index.tsx
import { component$, useSignal, $ } from "@builder.io/qwik";
import { type DocumentHead, useNavigate } from "@builder.io/qwik-city";
import { api } from "../../utils/api";
import { setAuth } from "../../stores/auth";

export default component$(() => {
  const username = useSignal("");
  const password = useSignal("");
  const error = useSignal("");
  const loading = useSignal(false);
  const nav = useNavigate();

  const handleSubmit = $(async () => {
    error.value = "";
    if (!username.value || !password.value) {
      error.value = "请输入用户名和密码";
      return;
    }
    loading.value = true;
    try {
      const res = await api.login({ username: username.value, password: password.value });
      setAuth({ token: res.token, role: res.role, username: res.username });
      nav("/");
    } catch (e: any) {
      error.value = e.message || "登录失败";
    } finally {
      loading.value = false;
    }
  });

  return (
    <div class="min-h-screen bg-bg flex items-center justify-center">
      <div class="bg-white rounded-xl shadow-lg p-8 w-full max-w-md">
        <div class="text-center mb-8">
          <div class="text-3xl mb-2">📋</div>
          <h1 class="text-xl font-bold text-stone-800">审核单系统</h1>
          <p class="text-sm text-stone-500 mt-1">家政服务平台 · 月底集中处理</p>
        </div>
        <div class="space-y-4">
          <div>
            <label class="block text-sm font-medium text-stone-700 mb-1">用户名</label>
            <input
              type="text"
              value={username.value}
              onInput$={(_, el) => (username.value = el.value)}
              onKeyDown$={(e) => { if (e.key === "Enter") handleSubmit(); }}
              class="w-full border border-stone-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary"
              placeholder="请输入用户名"
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-stone-700 mb-1">密码</label>
            <input
              type="password"
              value={password.value}
              onInput$={(_, el) => (password.value = el.value)}
              onKeyDown$={(e) => { if (e.key === "Enter") handleSubmit(); }}
              class="w-full border border-stone-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary"
              placeholder="请输入密码"
            />
          </div>
          {error.value && (
            <div class="text-sm text-status-red bg-red-50 rounded-lg px-3 py-2">
              {error.value}
            </div>
          )}
          <button
            onClick$={handleSubmit}
            disabled={loading.value}
            class="w-full bg-primary text-white rounded-lg py-2.5 text-sm font-medium hover:bg-primary-dark transition-colors disabled:opacity-50"
          >
            {loading.value ? "登录中..." : "登 录"}
          </button>
        </div>
        <div class="mt-6 text-xs text-stone-400">
          <p class="font-medium mb-1">演示账号：</p>
          <p>dispatcher / demo123 — 派单客服</p>
          <p>supervisor / demo123 — 服务督导</p>
          <p>manager / demo123 — 城市经理</p>
        </div>
      </div>
    </div>
  );
});

export const head: DocumentHead = {
  title: "登录 - 审核单系统",
};

// frontend/app/routes/login.tsx
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { useAuth } from "../lib/auth";

export const Route = createFileRoute("/login")({
  component: LoginPage,
});

function LoginPage() {
  const [username, setUsername] = useState("registrar1");
  const [password, setPassword] = useState("123456");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      await login(username, password);
      navigate({ to: "/orders" });
    } catch (e) {
      setError(e.message || "登录失败");
    } finally {
      setLoading(false);
    }
  };

  const demoAccounts = [
    { username: "registrar1", name: "张登记", role: "入职办理登记员" },
    { username: "auditor1", name: "李审核", role: "入职办理审核主管" },
    { username: "reviewer1", name: "王复核", role: "企业人事共享中心复核负责人" },
    { username: "registrar2", name: "赵登记", role: "入职办理登记员" },
  ];

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100 p-4">
      <div className="bg-white rounded-xl shadow-xl p-8 w-full max-w-md">
        <div className="text-center mb-8">
          <h1 className="text-2xl font-bold text-gray-800">企业人事共享中心</h1>
          <p className="text-gray-500 mt-2">月底集中处理入职办理单系统</p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">用户名</label>
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              placeholder="请输入用户名"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">密码</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              placeholder="请输入密码"
            />
          </div>

          {error && (
            <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg text-sm">
              {error}
            </div>
          )}

          <button
            type="submit"
            disabled={loading}
            className="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-lg transition disabled:opacity-50"
          >
            {loading ? "登录中..." : "登录"}
          </button>
        </form>

        <div className="mt-8">
          <p className="text-sm text-gray-500 mb-3">演示账号（密码均为 123456）：</p>
          <div className="space-y-2">
            {demoAccounts.map((acc) => (
              <button
                key={acc.username}
                onClick={() => {
                  setUsername(acc.username);
                  setPassword("123456");
                }}
                className="w-full text-left px-3 py-2 bg-gray-50 hover:bg-gray-100 rounded-lg text-sm flex justify-between items-center transition"
              >
                <span className="font-medium text-gray-700">{acc.name}</span>
                <span className="text-gray-500">{acc.role}</span>
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
